### ISSUE TITLE
HorizontalScrollBar in SukiWindow not show!is this a BUG?

### ISSUE THREAD

**Issue by strongQ** [kikipoulet/SukiUI#101]
# bug?
I hava a page add the scrollviewer control, when add some items , height and width is set,i think it should show HorizontalScrollBar and VerticalScrollBar,but it only show VerticalScrollBar,not show HorizontalScrollBar。i try set a border width and height in the page,also not show HorizontalScrollBar,avalonia bug or sukiui bug?
# code
```
<ScrollViewer >	
	<ItemsControl  Height="1000" Width="1000" ItemsSource="{Binding Datas}"  >
		<ItemsControl.ItemsPanel>
			<ItemsPanelTemplate>				
				<Canvas  />				
			</ItemsPanelTemplate>
		</ItemsControl.ItemsPanel>
		<ItemsControl.ItemContainerTheme>
			<ControlTheme TargetType="ContentPresenter">
				<Setter Property="Canvas.Top" Value="{Binding Top}"/>
				<Setter Property="Canvas.Left" Value="{Binding Left}"/>
			</ControlTheme>
		</ItemsControl.ItemContainerTheme>
		<ItemsControl.ItemTemplate>
			<DataTemplate>
				<cp:UnitTag></cp:UnitTag>
			</DataTemplate>
		</ItemsControl.ItemTemplate>
	</ItemsControl>

</ScrollViewer>
```
# picture
![picture](https://github.com/kikipoulet/SukiUI/assets/16400136/51bffa68-1197-4cfc-b5be-d4b65b09a18c)

**Comment by sirdoombox** [comment]
The default value for `HorizontalScrollbarVisibility` is `Disabled`
Have you tried:
```axaml
<ScrollViewer HorizontalScrollBarVisibility="Auto">
```
or 
```axaml
<ScrollViewer HorizontalScrollBarVisibility="Visible">
```

**Comment by strongQ** [comment]
@sirdoombox  谢谢！
