### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#109]
How to enable hot reload for this app?

I can't find a proper way to enable hot reload for it according to Avalonia document.

**Comment by kikipoulet** [comment]
Avalonia has no hot reload feature.

However there are two experimental open source projects that try to do it : 

https://github.com/AvaloniaUI/Live.Avalonia 
https://github.com/Kir-Antipov/HotAvalonia

Avalonia team is thinking about developing this feature for a "pro" paid subscription (https://github.com/AvaloniaUI/Avalonia/discussions/14097)
