### ISSUE TITLE
Dialog await problem

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#117]
Since SukiHost.ShowDialog() is a void function, I can't use await to wait until the function ends.
Can it be turned to a async function?

**Comment by yuzh0816** [comment]
Fixed in #118 .

**Comment by Insire** [comment]
Why do you need an ``await`` ?

**Comment by yuzh0816** [comment]
> Why do you need an ``await`` ?

I need to get the result like **Yes** or **No** from the dialog,.

**Comment by kikipoulet** [comment]
Another easy possibility as sirdoombox suggested is to use your ShowDialogAsync method from your PR as an extension method in your project.

I'm closing the issue as not planned but maybe one day we will implement a better overall API for dialog and confirmations
