### ISSUE TITLE
How to implement parameter passing from a Dialog component to a Window

### ISSUE THREAD

**Issue by mugongliu1** [kikipoulet/SukiUI#122]
"How to implement parameter passing from a Dialog component to a Window? Please provide an example for reference, thank you."

**Comment by CyLuGh** [comment]
I began using SukiUI very recently, but fro, what I saw, the OpenDialog returns void and isn't awaitable like some libraries do. So I use the MVVM pattern (with ReactiveUI in my case) to pass parameters back.

**Comment by mugongliu1** [comment]
> provide an example for

Could you provide an example ？
I use like this: SukiHost.ShowDialog(new Grid(), allowBackgroundClose: true);
But I don't know how to pass a parameter from Grid to the MainWindow

**Comment by CyLuGh** [comment]
You won't be able to do it using the UI library only.

I can show the very early work in progress I'm working on during my free time.

I open the dialog here: https://github.com/CyLuGh/rxingots/blob/suki/src/Ingots.Avalonia/Views/AccountsView.axaml.cs

```csharp
var vm = Locator.Current.GetService<AccountEditionViewModel>()!;
vm.Account = ctx.Input;
SukiHost.ShowDialog( new AccountEditionView(){ViewModel = vm}, allowBackgroundClose: true );
```

And the viewmodel is able to close the dialog itself, after triggering a return call: https://github.com/CyLuGh/rxingots/blob/suki/src/Ingots.ViewModels/AccountEditionViewModel.cs

```csharp
AddAccount.InvokeCommand( CloseDialog ).DisposeWith( disposables );
```

```csharp
CloseDialog = ReactiveCommand.CreateFromObservable( () => CloseDialogInteraction.Handle( RxUnit.Default ) );
```

```csharp
viewModel.CloseDialogInteraction.RegisterHandler( _ => SukiHost.CloseDialog() ).DisposeWith( disposables );
```

You can learn more about MVVM here: https://www.reactiveui.net/docs/getting-started/

---

You can certainly do things in a dirtier way by creating your Grid before the call to the open dialog and giving it a reference to your window.

**Comment by kikipoulet** [comment]
Thanks @CyLuGh for the quite complete answer, I would personally use MVVM too and pass a DataContext.

I would add that you can see this [PR](https://github.com/kikipoulet/SukiUI/pull/118) to have more informations.
