### ISSUE TITLE
SukiSideMenu when the sidebar is not available on Android?

### ISSUE THREAD

**Issue by WCKYWCKF** [kikipoulet/SukiUI#124]
The SukiSideMenuItem option generated in the sidebar does not react when clicked.

**Comment by WCKYWCKF** [comment]
On SukiUI 6.0.0.

**Comment by sirdoombox** [comment]
SukiUI is developed for and only tested on Desktop specifically.

Some things _might_ work on mobile, but they're not something that is actively supported.

**Comment by kikipoulet** [comment]
As sirdoombox said, SukiUI is developed for desktop and lots of its features is dependant to the "SukiWindow" used in the library - so tightly linked to desktop.

Moreover, as someone who is quite passionate about UI/UX, I would add that SukiUI and desktop controls in general are not well suited for mobile and would create bad design and interaction.

However I have a secondary library (https://github.com/kikipoulet/CherylUI) which is specifically made for mobile, I would advise you to use this one for mobile development.

**Comment by WCKYWCKF** [comment]
Thank you for your help.
