### ISSUE TITLE
How to change App icon?

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#128]
I've noticed that during the recent commit, the demo app has its icon displayed in the Windows tray. How to change/set that icon?

[I've also seen that you have put the demo app onto ms store, cool! But the icon has transparent problem with its background, have you noticed that?]

**Comment by sirdoombox** [comment]
For setting the icon, it's as simple as setting the `Icon` property of the `SukiWindow` (or in Avalonia, just the `Window`).

[Here is how we do it in the demo app, though this is probably a little unnecessary just a holdover from some old code.](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI.Demo/SukiUIDemoView.axaml.cs#L22)

As for the icon's transparent background I did notice and I have no idea why that is happening, it doesn't happen in debug on Windows only in the app store...
