### ISSUE TITLE
DataGrid as a separate package

### ISSUE THREAD

**Issue by Mrxx99** [kikipoulet/SukiUI#129]
I think it would make sense to publish a separate package for the DataGrid. This would reduce unnecessary dependency on DataGrid and reduce size if not needed.

As this would be a breaking change, the upcoming 6.0 would be a good candidate to introduce this.

**Comment by sirdoombox** [comment]
I think this is a fairly reasonable ask, but it does involve a bit more of a maintenance headache going forward.

`Avalonia.Controls.DataGrid` _is_ installed implicitly by default in new projects and I personally consider it a primitive control that really shouldn't be a separate package to begin with.

**Comment by Mrxx99** [comment]
It's not installed in new projects implicitly, it just looks like it is, because the DevTools use it, but as soon as you do a release build it's gone and build will fail if used

**Comment by Mrxx99** [comment]
> ... it does involve a bit more of a maintenance headache going forward.
> 
>

You could look how Material.Avalonia does it, they use a clever way so you don't have to add another StyleInclude when referencing the DataGrid package

**Comment by kikipoulet** [comment]
In addition to what sirdoombox said, I would add that SukiUI is not meant to be a lightweight library. It is highly animated by default and the controls themes aim to have a specific look and behavior without trying to minimise the visual tree over look.

So, I wouldn't advise to use it for embedded devices for example, where you would look to optimise the executable size and application performance, as I'm not convinced it would run at 60fps right now, it's highly focused on desktop. (And to me datagrid is a primitive control too).

Moreover, you can publish your application using the trimming option that will not include that assembly in your app if you're not using it. (If I'm correct)

For these reasons we choose the simplicity to include it. But I keep that in mind if more people's find it interesting to proceed like that. (People's that would use only the datagrid theme ?)
