### ISSUE TITLE
MobileNumberPicker MVVM Support

### ISSUE THREAD

**Issue by nixtar** [kikipoulet/SukiUI#13]
Hello,

I've been playing around with MobileNumberPicker and am finding the lack of value change notifications a bit cumbersome.

I'm not too familiar with AvaloniaProperties but looking at the built-in controls I see they use `SetAndRaise` instead of `SetValue` for these kinds of properties.

I've cloned SukiUI and did the following changes to `MobileNumberPicker.axaml.cs`:

From:
```c#
    public static readonly StyledProperty<int> ValueProperty =
        AvaloniaProperty.Register<MobileNumberPicker, int>(nameof(Value), defaultValue: 5);

    public int Value
    {
        get { return GetValue(ValueProperty); }
        set { SetValue(ValueProperty, value ); }
    }
```
To:
```c#
    private int _value;
    
    public static readonly DirectProperty<MobileNumberPicker, int> ValueProperty =
        AvaloniaProperty.RegisterDirect<MobileNumberPicker, int>(nameof(Value), numpicker => numpicker.Value,
            (numpicker, v) => numpicker.Value = v, defaultBindingMode: BindingMode.TwoWay, enableDataValidation: true);

    public int Value
    {
        get { return _value; }
        set
        {
            SetAndRaise(ValueProperty, ref _value, value);
        }
    }
```

Not sure if this is the "proper" way or if this will cause other issues but it works in my narrow use case.

I see MobileNumericUpDown has the same lack of change notifications also.
Happy to put forward a PR if this is an appropriate method?

**Comment by kikipoulet** [comment]
I think this is in fact the appropriate method ! 
A PR is welcomed :)

**Comment by nixtar** [comment]
Sounds good, I'll do a bit more research into `StyledProperty` vs `DirectProperty` so I have half a clue on what I'm doing from an Avalonia perspective, then look at updating the properties that should be bindable/observable and send over a PR.

Not sure how deep you want to go with this, should all controls that use `SetValue` for Value/SelectedItem properties be refactored?

While looking into `StyledProperty` vs `DirectProperty` I'll have a peek at some of the other Avalonia UI control libs and see how they handle this.

PS Thanks for your ongoing work on SukiUI, the controls are awesome! ❤

**Comment by kikipoulet** [comment]
Oh thank you I really appreciate !

To me, this is the weakest side of the project where I didn't dig a lot.
So any improvement is really welcome, I think there is a big room for C# code improvement in the library, a deeper refactoring could be appropriate.

**Comment by kikipoulet** [comment]
Started to change some controls for MVVM Compatibility  ( cdc9cf077a721ffaa707962af58dfa5ce77578fa )
Changing StyledProperty to DirectProperty is working well 👍

**Comment by nixtar** [comment]
Sweet 👍

I've created a draft PR #14 with MobileNumberPicker
