### ISSUE TITLE
 SukiHost.ShowDialog becomes ineffective

### ISSUE THREAD

**Issue by mugongliu1** [kikipoulet/SukiUI#134]
I have two sukiWindows, one of which is a login window. After the login is completed, one sukiWindow is closed, and the other sukiWindow is launched. Then calling SukiHost.ShowDialog becomes ineffective.
The login window closes, and the code to open another sukiWindow is as follows:
![PixPin_2024-02-18_09-48-58](https://github.com/kikipoulet/SukiUI/assets/42706017/3b6ab0f3-3948-4a94-aadb-dba0b8f60cae)

**Comment by kikipoulet** [comment]
This is indeed one of our problem. As Avalonia does not have built-in Dialog System, we wanted to make a super simple one. 
However, as it relies on singletons to be called anywhere, it does not support multiple SukiWindows well. So basically only your first SukiWindow will get it.

More info : https://github.com/kikipoulet/SukiUI/issues/115

I had already thought that we could do a window style to have the style of SukiWindow for other windows and keep the Dialog system of the SukiWindow for the mainwindow.

**Comment by sirdoombox** [comment]
Yeah right now the current implementation, which was only really meant to be temporary, attaches to the first-opened window once at instantiation and that's it.

There are some things I could do which would make this work better, and perhaps open it up to be addressable per-window.

I can take a look to see what the absolute minimum changes I'd need to make to make this happen, assuming I can do it without breaking the existing API (which should be possible) then it can probably make the 6.0 release.

**Comment by mugongliu1** [comment]
Thank you for the prompt reply. I am very much looking forward to the next version update to fix this feature.
