### ISSUE TITLE
TextBlock in CheckBox couldn't change color with base theme

### ISSUE THREAD

**Issue by TianYi-TY-zh** [kikipoulet/SukiUI#135]
I use two ways to show the check box with text box,now if I change base theme,the A text box will keep in black color,but B text box will change
![issue](https://github.com/kikipoulet/SukiUI/assets/85554260/29fb0674-a32e-408c-ae58-ed9940ffa09c)
![issue2](https://github.com/kikipoulet/SukiUI/assets/85554260/4cfdd617-bec0-4dc2-922c-e003b37aecc3)

**Comment by kikipoulet** [comment]
Thank you for the feedback

Fixed in commit 073651b51ca0773166b1d6d0598085e230186ad3

Note that you can also simply use <Checkbox Content="A" /> syntax
