### ISSUE TITLE
DefaultTextBoxContextFlyout looks awkward on dark theme

### ISSUE THREAD

**Issue by Bia10** [kikipoulet/SukiUI#136]
![image](https://github.com/kikipoulet/SukiUI/assets/2548763/2c0d0b58-06da-41ef-bbec-d61ec3723f41)

vs

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/1930c0e6-ec83-4629-8395-7e02b08ed210)

**Comment by kikipoulet** [comment]
It is indeed not even styled yet, thanks for telling me.

I add it on my to-do list 👀
