### ISSUE TITLE
ComboBox dropdown shows weird margin.

### ISSUE THREAD

**Issue by huestack** [kikipoulet/SukiUI#139]
Hi,
The ComboBox dropdown shows white margin container. 

This screenshot shows packages installed, the code, and the running window:
![image](https://github.com/kikipoulet/SukiUI/assets/11208563/3be9254a-7d40-4efb-ac46-41bf01ece006)

I am using version 5.3.0, and added Suki theme with
 
 ```
 <StyleInclude Source="avares://SukiUI/Theme/Index.xaml" />
 ```
 
Also, Window class `NakedWindow` makes the window dark. How can I make it light?

**Comment by CyLuGh** [comment]
I think you have to use the 6.0.0 beta with the latest avalonia.

**Comment by kikipoulet** [comment]
Your configuration seems .. complex. 

Do you use NativeAOT? I saw the exact same bug in the SukiUI Demo App compiled with NativeAOT.

If you're curious btw - SukiUI Demo App NativeAOT : https://drive.filen.io/d/71b473d1-17c2-4fd4-ba51-cc3a98458503#uaKKtNDPGumDVdKya713h3M54fPIYPL4

Otherwise I would say that Suki 5.3 hasn't been tried with Avalonia 11.9 and that lots of breaking changes happen between versions so I'm not really surprised. I advice you to use SukiUI 6.0 preview, just because of the massive performance improvements too.

**Comment by huestack** [comment]
@CyLuGh It's same with latest beta:
![image](https://github.com/kikipoulet/SukiUI/assets/11208563/1a2c070d-708f-490a-8a47-94f6f5a7cb7d)

@kikipoulet No, my basic app is not NativeAOT. Also, your demo app didn't even start. FWIW, my system is Windows 2016 running in VirtualBox VM.

**Comment by huestack** [comment]
@kikipoulet An update. I just tested SukiUI `6.0.0-beta2` and `5.3.0`. in Windows 2019, and it works. I do no longer see the container margin.  However, 5.3.0 is still buggy.

Regarding windows version, I assume `6.0.0-beta2` must work in Windows 10+ as well. It'd be better if it could work on Windows 2016 as well, as my app will run on server and desktop windows. Will test on Win 10 and let you know.

**Comment by kikipoulet** [comment]
Actually I think it is more an Avalonia limitation about platform support, Windows 7 is not supported for example, so : 

- If Combobox act the same in your configuration with another theme (like fluenttheme), it is just a platform support problem from Avalonia.

- If it is specific to SukiUI in this configuration, it means that the animations and transitions features that SukiUI generously use aren't really supported on the platform anymore.

Note that the version of Avalonia is important, suki 5.3 was for Avalonia 11.0.5. Using it with Avalonia 11.0.9 can definitely cause this bug, I have seen worse between minor versions changes.

**Comment by huestack** [comment]
@kikipoulet It makes sense about Avalomia version and support. I ran Fluent Dark theme on Windows 2016, and it did show some irregularities, however it works well in 2019.

Anyway, I do like SukiUI so far. Is there any date decided when version 6 coming out of beta?

Thank you for your help and work on SukiUI.

**Comment by kikipoulet** [comment]
> @kikipoulet It makes sense about Avalomia version and support. I ran Fluent Dark theme on Windows 2016, and it did show some irregularities, however it works well in 2019.
> 
> Anyway, I do like SukiUI so far. Is there any date decided when version 6 coming out of beta?
> 
> Thank you for your help and work on SukiUI.

You're welcome, thank you for the feedback.

I plan to publish a 3rd and last preview in few days. Now, the "release" won't have any breaking changes, I'll just wait a few weeks without issues to publish a release, so I don't expect any real change.
