### ISSUE TITLE
Button within textblock doesnt work

### ISSUE THREAD

**Issue by Bia10** [kikipoulet/SukiUI#147]
this 

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/27776377-aafd-4548-b066-7b26a658726e)

produces

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/e6d95854-388d-4775-b665-5240c12d7f82)

and the nav service is never called

seems to work fine when not embeded in TextBlock

**Comment by sirdoombox** [comment]
I assume this is just the button in the splash page from the demo app as it currently is running attached to your IDE?

An unfortunate case of "works on my machine" here, can't seem to reproduce this one, however Avalonia has been going through it with textblock runs so if there is an issue, it might well be with Avalonia in this case.

If you changed anything let me know so I can try and get this issue repro'd on my end.

**Comment by kikipoulet** [comment]
What is the Avalonia version used ? We can have some weird breaking changes between minor versions.

**Comment by Bia10** [comment]
> What is the Avalonia version used ? We can have some weird breaking changes between minor versions.

Its repo on latest commit, the only thing modified is added serilog sink..

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/04d6c4a1-5b51-42f5-9f65-b6e65ff5aac5)

on WIN 10 latest x64

**Comment by Bia10** [comment]
Not sure when or how this fixed itself, but as of now unable to reproduce, memory allocation also dropped by ~50%.
