### ISSUE TITLE
Some ideas around PlaygroundView and its CompletionList

### ISSUE THREAD

**Issue by Bia10** [kikipoulet/SukiUI#149]
Some things id like to see. So i am asking which of these points we can/should adress and which should be left to AvaloniaEdit project.

## Allow use of right click for caret movement in editor

Since right click is not used for anything at the moment, not invoking any flyout it would be nice to make it move the caret.

## The CompletionList is created without any item of its listBox selected

This leads to ability of running insertion on empty space.

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/72a4a5d0-649f-4664-8bc6-d0284ea73b06)

1. we could check if selectedItem == null

And throwing a toast that no completion list item was selected.

2. we could fix selectedItem to First() on creation of completionList

This would also make it apparent that you have to select items to be AutoCompleted first, personally i was a bit lost why it was always just closing the completionList on single leftClick on MouseOverSelected item.

## Better mouse handling

1. Theres a problem that mouseOver the item in scrollViewer has its own selection which conflicts which the completionList selected item.

mouse focus is bound to seletec item after right click:

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/146bcaba-a617-4a88-b5d8-e980be30e37b)

after left click in completion list, mouse selection is unbound from selected item:

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/24f66d00-c32d-451e-aa93-53a557030b9c)

CompletionListSelectedItem -> GlassCard
MouseOverSelectedItem -> Button

2. Simply using left click when no item is selected just closes the CompletionList.

This leads to question if it would not be worth it to create mouse event handler for the CompletionList and map the mouseOver selectedItem to the completionList selected item.

Not rly sure how this would be implemented getting VisualChildren and quering the listBox items?
Making custom hitTest for the listBox items under cursor?

But certainly it would be nice to automaticaly select items which are under mouse pointer.

## Dont constatly rerender on each character input

I would prefer if there were 2 buttons Render and Reset

as currently for whatever char u type it tries to render and simply constatly spams exceptions bcs the Xaml is not yet valid for XamlParser to process it and pointlessly has to produce exceptions as you type.

## Change the xaml in the PlaygroundView.cs to readonly raw strings

```C#
        private readonly string StartingString =
            """
            <suki:GlassCard Width="300" Height="320" Margin="15" VerticalAlignment="Top">
                <Grid>
                    <TextBlock FontSize="16" FontWeight="DemiBold" Text="Humidity" />
                    <Viewbox Width="175" Height="175" Margin="0,0,0,5" HorizontalAlignment="Center" VerticalAlignment="Center">
                        <suki:WaveProgress Value="{Binding Value, ElementName=SliderT}" />
                    </Viewbox>
                    <DockPanel VerticalAlignment="Bottom">
                        <icons:MaterialIcon Width="20" Height="20" DockPanel.Dock="Left" Foreground="#666666" Kind="TemperatureLow" /> 
                        <icons:MaterialIcon Width="20" Height="20" DockPanel.Dock="Right" Foreground="#666666" Kind="TemperatureHigh" />
                        <Slider Name="SliderT" Margin="8,0" Maximum="100" Minimum="0" Value="23" />
                    </DockPanel>
                </Grid>
            </suki:GlassCard>
            """;
```

**Comment by kikipoulet** [comment]
I think that these are good ideas, but we unfortunately don't have time to improve the playground part as we're just focusing on solving issue and make it ready for a release. To me it's just a kind of "gimmick".

However, if you're willing to improve the playground experience to be closer to an IDE experience, I would be glad to accept your PR to improve it👍

**Comment by Bia10** [comment]
Sure, i was just unsure if it shall be tackled on our side, i will work on it.

Btw expanding the scrollviewer listbox with more items, glitch appeared. Not sure if this is bug or just lack styling implementation for this.

![image](https://github.com/kikipoulet/SukiUI/assets/2548763/5aba23de-305f-48eb-958b-36e879dbe67b)

**Comment by kikipoulet** [comment]
> Sure, i was just unsure if it shall be tackled on our side, i will work on it.
> 
> Btw expanding the scrollviewer listbox with more items, glitch appeared. Not sure if this is bug or just lack styling implementation for this.
> 
> ![image](https://private-user-images.githubusercontent.com/2548763/308910454-5aba23de-305f-48eb-958b-36e879dbe67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTE4MjMsIm5iZiI6MTcwOTIxMTUyMywicGF0aCI6Ii8yNTQ4NzYzLzMwODkxMDQ1NC01YWJhMjNkZS0zMDVmLTQ4ZWItOTU4Yi0zNmU4NzlkYmU2N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTI1ODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk5NWE3ZmQ0NDQzOTg3Yjg3N2I3OTA4NzA1MDM3Y2VlMmExYjMzNzk3ZmI3OGUwMDEzM2EzNTgyNjI1ODMzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UTGldjlwMGcrfLxUcICKl16M6dANbSGgm9CxOa3o3kY)

Oh cool, you can contact me on discord ( 'KoalaKoala' ) if you want to discuss more of it. I'm closing this for readability.

I will take a look on scrollviewer style.
