### ISSUE TITLE
Does Suki support $Parent syntax?

### ISSUE THREAD

**Issue by zimuyanghua** [kikipoulet/SukiUI#158]
**Describe the bug**
I want the visibility of the usercontrol to be determined by the properties of the parent window. In the same way, the official template can be compiled and runs normally, but it can't be compiled in suki.

![image](https://github.com/kikipoulet/SukiUI/assets/46125819/7e3fd734-092f-4301-9fbf-820a8654bf08)
![image](https://github.com/kikipoulet/SukiUI/assets/46125819/01c1362f-4bc8-4dbd-a648-aafc74db92d2)

The compilation in rider is normal, but the operation error is reported
![image](https://github.com/kikipoulet/SukiUI/assets/46125819/1c6241bb-ee0f-4b26-8651-6d662e37412f)

> Unhandled exception. System.ArgumentException: Unable to resolve type view:MainWindow from any of the following locations: 
>    at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.XamlTypeResolver.Resolve(String qualifiedTypeName)
>    at Avalonia.Markup.Xaml.Extensions.ResolveType(IServiceProvider ctx, String namespacePrefix, String type)
>    at Avalonia.Markup.Parsers.ExpressionParser.ParseFindAncestor(AncestorNode node)
>    at Avalonia.Markup.Parsers.ExpressionParser.Parse(CharacterReader& r)
>    at Avalonia.Markup.Parsers.ExpressionObserverBuilder.Parse(String expression, Boolean enableValidation, Func`3 typeResolver, INameScope nameScope)
>    at Avalonia.Data.Binding.CreateExpressionObserver(AvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation)
>    at Avalonia.Data.BindingBase.Initiate(AvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation)
>    at Avalonia.AvaloniaObjectExtensions.Bind(AvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
>    at sukiDemo.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in D:\Project\sukiDemo\sukiDemo\Views/MainWindow.axaml:line 31
>    at sukiDemo.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow ) in D:\Project\sukiDemo\sukiDemo\Views/MainWindow.axaml:line 0
>    at sukiDemo.Views.MainWindow.InitializeComponent(Boolean loadXaml, Boolean attachDevTools) in D:\Project\sukiDemo\sukiDemo\Avalonia.Generators\Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator\sukiDemo.Views.MainWindow.g.cs:line 23
>    at sukiDemo.Views.MainWindow..ctor() in D:\Project\sukiDemo\sukiDemo\Views\MainWindow.axaml.cs:line 12
>    at sukiDemo.App.OnFrameworkInitializationCompleted() in D:\Project\sukiDemo\sukiDemo\App.axaml.cs:line 24
>    at Avalonia.AppBuilder.SetupUnsafe()
>    at Avalonia.AppBuilder.Setup()
>    at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
>    at sukiDemo.Program.Main(String[] args) in D:\Project\sukiDemo\sukiDemo\Program.cs:line 14

** Environment
- windows 11
- Avalonia-Version:11.0.6
- SukiUI:6.0.0-beta3

**Comment by kikipoulet** [comment]
It is not related to SukiUI I think, as it just can't find your MainWindow.
I have tried on my side and it works. I suggest you to use the SukiWindow type "$parent[suki:SukiWindow]" as an alternative.

**Comment by zimuyanghua** [comment]
@kikipoulet I changed the code, mainwindow does not report an error, but now it says that the vm cannot be found
![image](https://github.com/kikipoulet/SukiUI/assets/46125819/b6df1da9-7d4b-408f-8a36-b96bedca2a31)

**Comment by zimuyanghua** [comment]
@kikipoulet I modified the way the viewmodel was written according to your idea, and found it successful
> xmlns:vm="clr-namespace:SukiApp.ViewModels"

But this way it will give an error:
> xmlns:vm="using:SukiApp.ViewModels"

**Comment by zimuyanghua** [comment]
I use `clr-namespace` instead of `using`, and I can also use `view:MainWindow`, isn't `using` the same as` clr-namespace`?

**Comment by zimuyanghua** [comment]
After setting the `CompileBindings` to true, the program is normal.😅

`<view:Main 
      x:CompileBindings="True"
      IsVisible="{Binding $parent[view:MainWindow].((vm:MainWindowViewModel)DataContext).IsVisible}"/>`
