### ISSUE TITLE
Error with tray icon style.

### ISSUE THREAD

**Issue by WCKYWCKF** [kikipoulet/SukiUI#159]
**Describe the bug**
You don't seem to have finished styling the system tray section.

**To Reproduce**

1. Complete the basic SukiUI settings.
2. Follow https://docs.avaloniaui.net/docs/reference/controls/detailed-reference/tray-icon to set the tray icon.
3. The theme is set to dark.
4. Right-click to open the menu.
5. Look for styling errors.

**Expected behavior**
It should follow the style of SukiUI. At least don't go wrong with the color.

**Screenshots**
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/6f6e9d69-3c92-4e78-9a22-27cccf11912b)

** Environment**
- Windows 11
- Avalonia 11.0.10
- The source code of SukiUI
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/aa359f16-27d7-487d-bda3-63c2d08ba86d)

**Comment by kikipoulet** [comment]
System tray section is indeed not styled at all. I will style it one day when I will have time.

**Comment by WCKYWCKF** [comment]
Hello.
I made the following changes to the project, and things seem to have improved.

**Operate**

1. Install Nuget as follows:
- Avalonia 11.1.0-beta1
- Avalonia.Desktop 11.1.0-beta1
- Avalonia.Diagnostics 11.1.0-beta1
- Avalonia.Fonts.Inter 11.1.0-beta1
- Avalonia.ReactiveUI 11.1.0-beta1
- Avalonia.Themes.Fluent 11.1.0-beta1
- SukiUI 6.0.0-beta4
- Avalonia.Native 11.1.0-beta1
2. Avalonia.Native 11.1.0-beta1 is new.

**Effect**
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/9cd753b7-cce3-4634-b2c7-569f398b96d8)
The menu color of TrayIcon.Icons is not wrong, but the font is very blurry.

Looking forward to your next update.
