### ISSUE TITLE
The FontSize property of the TextBox is invalid.

### ISSUE THREAD

**Issue by WCKYWCKF** [kikipoulet/SukiUI#161]
**Describe the bug**
When the project introduces SukiUI, the FontSize property of the TextBox is invalid. Regardless of the value of the FontSize, the font size displayed by the TextBox will not change.

**To Reproduce**

1. Create a standard Avalonia blank desktop project.
2. Follow the instructions on the homepage of SukiUI to install SukiUI.
3. When you remove <sukiUi:SukiTheme ThemeColor="Blue" /> and SukiWindow inheritance, the FontSize property of the TextBox is normal.
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/6efe1cab-85bb-4ffd-815c-b20aeabdb12d)
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/d5f2f1a2-ddb5-4332-b0e4-9b4e7030bd2e)

5. When you add <sukiUi:SukiTheme ThemeColor="Blue" /> and SukiWindow inheritance, the FontSize property of the TextBox is invalidated.
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/adebb007-70d3-4a6d-8f23-16ace6e74185)
![image](https://github.com/kikipoulet/SukiUI/assets/82446104/3978c804-97c0-4465-9073-753fcd19d573)

**Expected behavior**
When using SukiUI, the FontSize property of the TextBox should take effect.

**Screenshots**

** Environment
- Windows 11
- Avalonia-11.0.10
- SukiUI 6.0.0-beta4

**Additional context**
Hi friends. Looking forward to you fixing this bug as soon as possible.

**Comment by kikipoulet** [comment]
fixed in #8d64915
