### ISSUE TITLE
Feature Request: Add Drawer Mode Support to SideMenu Component

### ISSUE THREAD

**Issue by j4587698** [kikipoulet/SukiUI#162]
Can the SideMenu support a drawer mode? Can it be opened in a way similar to a hamburger menu?
I would like to have an auto-sizing SideMenu, similar to [Avalonia.Shell](https://github.com/AvaloniaInside/Shell).

Thank you for considering this feature request.

**Comment by kikipoulet** [comment]
You mean with no compactpane and drawer overlay on content ? Is it for mobile purpose ?

**Comment by j4587698** [comment]
Yes, I aim to create an adaptive window that can cater to both desktop and mobile platforms simultaneously.

**Comment by kikipoulet** [comment]
Okay I understand what you're trying to do. Unfortunately I focus on desktop for SukiUI - and by the way I don't think SukiUI controls are adapted for mobile. (It's the reason I made CherylUI  https://github.com/kikipoulet/CherylUI ) 

Personnally, in such case, I prefer to do two different projects for mobile/desktop. To me the cross-platform advantage is not to everything in one view, it's just to master one front-end framework to make desktop/mobile apps. It's just my personal opinion obviously, just to explain why I focus SukiUI completely on desktop.

So unfortunately I won't have the time to adapt it for mobile sorry :(
