### ISSUE TITLE
Improperly styled busy buttons

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#163]
**Describe the bug**
The busy buttons seem to be improperly styled.

**To Reproduce**
Set the buttons to BUSY status.

**Expected behavior**
The refresh icon of the busy button should have the same color with the text.

**Screenshot**
![Screenshot](https://img2.imgtp.com/2024/04/04/4MCczFZO.png)

**Environment**
- Windows 11 23H2 22635.3420
- Avalonia

**Comment by kikipoulet** [comment]
fixed in 982f235
