### ISSUE TITLE
CalendarDatePicker background is transparent ; stays on top of other windows

### ISSUE THREAD

**Issue by blueperspective** [kikipoulet/SukiUI#164]
**Describe the bug**
The CalendarDatePicker, when showing the calendar, has a transparent background:
![sukiui_calendar_pb](https://github.com/kikipoulet/SukiUI/assets/22202667/f326257d-e2a9-47a1-9b4a-7100f14a059c)

No problem when the calendar is not shown.

And when switching with another window (from another app), it stays on top (see screenshot where it is in front of firefox, on SukiUi github page).
![2024-04-04 19_32_24-Issues · kikipoulet_SukiUI · GitHub — Mozilla Firefox](https://github.com/kikipoulet/SukiUI/assets/22202667/5e3baf9a-31bf-4ec3-8100-8c1fb6997e15)

**To Reproduce**
Add a CalendarDatePicker to a window.

```
<CalendarDatePicker SelectedDate="{Binding StartDate}" />
```

**Environment**

- OS : Windows 10
- Avalonia-Version : Avalonia 11.0.10

**Comment by blueperspective** [comment]
I know there is the DatePicker, which renders fine, but it is not replaceable 'as is', as it seems it does not support binding on the selected date.

**Comment by kikipoulet** [comment]
styled in 4fd901c
