### ISSUE TITLE
 error CS1061: “AppBuilder”未包含“UseXamlDisplay”的定义，并且找不到可接受第一个“AppBuilder”类型参数的可访问扩展方法“UseXamlDisplay”(是否缺少 using 指令或程序集引用?)

### ISSUE THREAD

**Issue by 525293680** [kikipoulet/SukiUI#166]
已经安装了ShowMeTheXaml，编译提示：
 error CS1061: “AppBuilder”未包含“UseXamlDisplay”的定义，并且找不到可接受第一个“AppBuilder”类型参数的可访问扩展方法“UseXamlDisplay”(是否缺少 using 指令或程序集引用?)
![1712473132084](https://github.com/kikipoulet/SukiUI/assets/34886258/50211ee7-ce11-469b-9127-d6e0f49f4aa1)

**Comment by Bia10** [comment]
Also got this after the 11.1 update, as workaround you can revert back to version 1.4.1

**Comment by 525293680** [comment]
Thank you for your suggestion.

**Comment by Jhonnyfish** [comment]
I commented UseXamlDisplay() and it compiles successfully, is there a better solution?

**Comment by Jhonnyfish** [comment]
> I commented UseXamlDisplay() and it compiles successfully, is there a better solution?


> Also got this after the 11.1 update, as workaround you can revert back to version 1.4.1

Its worked

**Comment by Eanvans** [comment]
reproduce this issue today, update ShowMeTheXaml package to 1.5.1 or above will solve the issue.

**Comment by kikipoulet** [comment]
should be fixed in latest beta5 nuget package
