### ISSUE TITLE
Why doesn't the hand shape display when the mouse moves to the menu navigation? I added a simple sentence, can I mention PR if possible

### ISSUE THREAD

**Issue by snake-L** [kikipoulet/SukiUI#169]

**Comment by kikipoulet** [comment]
can you show me precisely what you mean with a screenshot ?

**Comment by snake-L** [comment]
before ![image](https://github.com/kikipoulet/SukiUI/assets/49057777/42054fa1-20e3-494c-b364-263206645148) after ![image](https://github.com/kikipoulet/SukiUI/assets/49057777/cd1a1db5-7fdc-4566-8335-47fd9cb781ea)

**Comment by kikipoulet** [comment]
Well, that's an interesting behavior actually. You can make a PR if you want
