### ISSUE TITLE
Can't run cloned and/or downloaded project

### ISSUE THREAD

**Issue by jpgarza93** [kikipoulet/SukiUI#17]
Hello, 

I am trying to run the demo to see what type of controls are available. I am getting some errors when trying to run any of the MobileDemo projects using VS 22.

Here is an image of the errors I am getting when running MobileDemo.Desktop _(Debug) (Any CPU)_
![image](https://user-images.githubusercontent.com/79015116/211901811-a609dd42-9d78-45bf-8983-e4280852e615.png)

Any clues?

**Comment by kikipoulet** [comment]
These kind of silly errors sometimes appeared when upgrading Nuget package previews, so I guess that a Nuget restore, clean solution, etc .. could help.

The xplat template is usually really less stable so I'm not surprised. I struggled myself in all the upgrades ..
Do the SukiTest project runs ?

If you want to run on mobile I suggest you to start from the xplat template and then use SukiUI when the template runs
If you want to just see the controls, I tried to use as much gif as possible in the wiki to show the animations 👍

**Comment by kevkov** [comment]
Looks like there are local package references left over in SukiUI.csproj:

```csproj
      <Reference Include="Avalonia.Controls">
        <HintPath>..\..\..\..\..\.nuget\packages\avalonia\0.10.999-cibuild0019213-beta\lib\netstandard2.0\Avalonia.Controls.dll</HintPath>
      </Reference>
      <Reference Include="Avalonia.ReactiveUI">
        <HintPath>..\..\..\..\..\.nuget\packages\avalonia.reactiveui\0.10.999-cibuild0019213-beta\lib\netstandard2.0\Avalonia.ReactiveUI.dll</HintPath>
      </Reference>
```

**Comment by kikipoulet** [comment]
> Looks like there are local package references left over in SukiUI.csproj:

Oh nice catch, thank you you are my hero 👍 
I commited the changes, it can run only better without that !

**Comment by kevinha** [comment]
> Hello,
> 
> I am trying to run the demo to see what type of controls are available. I am getting some errors when trying to run any of the MobileDemo projects using VS 22.
> 
> Here is an image of the errors I am getting when running MobileDemo.Desktop _(Debug) (Any CPU)_ ![image](https://user-images.githubusercontent.com/79015116/211901811-a609dd42-9d78-45bf-8983-e4280852e615.png)
> 
> Any clues?

I updated all the Avalonia related packages to the latest (mainly 11.0.0-preview4 at the time of writing, but there are 1 or 2 with a different version) and it built and ran fine.

**Comment by kevinha** [comment]
Or, having looked a bit closer, there is an `AvaloniaVersion` variable in each of the project files which can be set using a `Directory.Build.props` file like this

```xml
<Project>
    <PropertyGroup>
        <AvaloniaVersion>11.0.0-preview4</AvaloniaVersion>
    </PropertyGroup>
</Project>
```
in the root of the solution.

**Comment by KluDev** [comment]
After updating all packages to version 11.0.0-preview4 I still get an error:

![grafik](https://user-images.githubusercontent.com/878677/214814583-7da34dab-ac09-4a88-8aa8-60514c4382f2.png)

**Comment by kikipoulet** [comment]
Are you running the SukiTest project or a project of yours ?

**Comment by KluDev** [comment]
I get this error in the user control  SukiUI/Controls/Stepper.axaml.cs in line 85.

**Comment by kikipoulet** [comment]
> I get this error in the user control SukiUI/Controls/Stepper.axaml.cs in line 85.

Sure, but which code is running ? It seems the "Steps" Property of the Stepper is not set. 
Are you running the SukiTest project or a project of your own ?


> I updated all the Avalonia related packages to the latest in nuget (mainly 11.0.0-preview4 at the time of writing, but there are 1 or 2 with a different version), rather than AvaloniaCI, and it built and ran fine.

To complete this answer, the MobileDemo project (cross-platform) is always more "sensitive" to dependencies change, but upgrading all the Avalonia packages to 11.4 preview works fine (just verified it on linux too).

SukiUI is on preview 11.1 right now and some small bugs can appear between the previews version. (For example the ToggleSwitch was broken between preview2 ans preview3 because the Thumb name changed in control, etc ..)
Nothing really serious, I am personally using 11preview4 on professional projects, but I'm waiting for Avalonia 11 Official Release to update SukiUI nuget package.

**Comment by KluDev** [comment]
I run the MobileDemo.Desktop project.
