### ISSUE TITLE
Unexpected `pointerover` events triggered in parent TreeViewItem

### ISSUE THREAD

**Issue by AuroraZiling** [kikipoulet/SukiUI#176]
**Describe the bug**
When the pointerover event is triggered on other same-level TreeViewItem while the child TreeViewItem is selected, the parent will accidentally trigger this event

**To Reproduce**
![ea70347fc3b0a700ab51b6f8d8a4acf3](https://github.com/kikipoulet/SukiUI/assets/69903523/cba48cd1-2d28-4df0-a6b8-6506e5a7e420)

**Expected behavior**
![b](https://github.com/kikipoulet/SukiUI/assets/69903523/9fc22401-79d2-4a4e-b197-b6676e687ec6)

**Environment**
- OS: Windows 11
- Avalonia-Version 11.1.10

**Additional context**
Bubbling? (but handling this event changes nothing)

**Comment by AuroraZiling** [comment]
I think it might be good to make it optional to highlight the parent TreeViewItem. If you do choose to highlight it, it will stay that way even if the pointerover event isn't triggered.

**Comment by kikipoulet** [comment]
Should be fixed on last commit e956e8e.
Thanks for the feedback  👍
