### ISSUE TITLE
how to order items in propertygrid?

### ISSUE THREAD

**Issue by Everyyx** [kikipoulet/SukiUI#177]
Hi,kikipoulet，I like your suki control very much, but I have some problems during use, like how to sort items in PropertyGrid, I tried some methods but it didn't work, do you have any good suggestions on your side

**Comment by Insire** [comment]
The PropertyGrid does not support changing the order of its categories and the entries inside. The default order is what ever is returned, when examining the bound class via reflection.

If you want to change that, then you can subclass the ``InstanceViewModel`` and override this [method](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/PropertyGrid/InstanceViewModel.cs#L50). Your custom implementation then, has to be assigned to [this ](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/PropertyGrid/PropertyGrid.axaml.cs#L36).
