### ISSUE TITLE
Chinese font display issue

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#192]
**Describe the bug**
When using Chinese characters in application, the weight of fonts may sometimes be very strange, but all fonts are applied with the same style.

**To Reproduce**
Code can be found [here](https://github.com/Uotan-Dev/UotanToolboxNT/blob/main/UotanToolbox/Features/Home/HomeView.axaml)

**Expected behavior**
All fonts are displayed in the same weight.

**Screenshots**

![1716011089130.png](https://github.com/kikipoulet/SukiUI/assets/46953451/b714bdbd-6ed0-4487-82e7-6dc57eb1897c)

**Environment**
- Windows
- Avalonia 11.0.6/11.1

**Comment by AuroraZiling** [comment]
FYI
https://github.com/kikipoulet/SukiUI/issues/165

**Comment by kikipoulet** [comment]
> FYI
> https://github.com/kikipoulet/SukiUI/issues/165

By the way, as it happens because the support of Quicksand font for Chinese seems very poor, maybe one day we could put an alternative Chinese font in a Style file that would rewrite the font resource if it's included in the App.axaml after the "SukiTheme" import 🤔

**Comment by AuroraZiling** [comment]
I would recommend `MiSans` that support 600+ languages

[MiSans - Latin](https://hyperos.mi.com/font/details/latin)
[MiSans - Chinese Simplified](https://hyperos.mi.com/font/zh/details/sc)
[MiSans License](https://hyperos.mi.com/font-download/MiSans%E5%AD%97%E4%BD%93%E7%9F%A5%E8%AF%86%E4%BA%A7%E6%9D%83%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE.pdf)

**Comment by yuzh0816** [comment]
> I would recommend `MiSans` that support 600+ languages
> 
> [MiSans - Latin](https://hyperos.mi.com/font/details/latin) [MiSans - Chinese Simplified](https://hyperos.mi.com/font/zh/details/sc) [MiSans License](https://hyperos.mi.com/font-download/MiSans%E5%AD%97%E4%BD%93%E7%9F%A5%E8%AF%86%E4%BA%A7%E6%9D%83%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE.pdf)

That works!

**Comment by kikipoulet** [comment]
@AuroraZiling, can you confirm that after last commit, it works to put 

`<StyleInclude Source="avares://SukiUI/CustomFont/MiSans/ChineseSupport.axaml"></StyleInclude>`

in app.axaml, after including sukitheme, to apply MiSans font and that it is satisfying for chinese ?

**Comment by AuroraZiling** [comment]
well, this doesn't work, perhaps because the `MiSans-Latin` font is used instead of the `MiSans` font (`MiSans-Latin` only supports languages in Latin)

I will fix it

**Comment by AuroraZiling** [comment]
One problem to consider is that `MiSans` with full language support seems to take up a lot of space (80 times that of Latin)
![image](https://github.com/kikipoulet/SukiUI/assets/69903523/94baf6c1-db5c-4f6f-baf8-f07169c28251)

**Comment by kikipoulet** [comment]
> I think Chinese font support should be implemented by the app developer, just like replacing QuicksandFont in app.axaml before, but I think it would be more reasonable to replace QuicksandFont with CustomFont as x:key.
> 
> For example: `<FontFamily x:Key="QuicksandFont">yourfont</FontFamily>`
> 
> Change: `<FontFamily x:Key="CustomFont">yourfont</FontFamily>`

My goal was to find a good chinese font to include and put it directly in SukiTheme, so peoples could use it like this :

```  
<Application.Styles>
        <sukiUi:SukiTheme ThemeColor="Blue" UseMiSansFont="True" />     
    </Application.Styles>
``` 

but it is indeed annoying if it means adding mbs of font for a majority of users who won't use it

**Comment by AuroraZiling** [comment]
There are three font variants that are more compatible with SukiUI:
Light: `ExtraLight`
Normal: `Light`
Heavy: `Normal`

**Comment by kikipoulet** [comment]
> There are only three font variants that are more compatible with SukiUI: Light: `ExtraLight` Normal: `Light` Heavy: `Normal`

@AuroraZiling  Can I ask you then to just add a simple lightweight (nice) chinese font in the CustomFont folder ? Then I will see an option to use it easily for chinese users, chinese support is a kind of priority as I kind of suspect that almost the majority of the users of the library are chinese friends 👀

**Comment by yuzh0816** [comment]
> > There are only three font variants that are more compatible with SukiUI: Light: `ExtraLight` Normal: `Light` Heavy: `Normal`
> 
> @AuroraZiling  Can I ask you then to just add a simple lightweight (nice) chinese font in the CustomFont folder ? Then I will see an option to use it easily for chinese users, chinese support is a kind of priority as I kind of suspect that almost the majority of the users of the library are chinese friends 👀

The nornal weight seems to be a bit light in the applicationapplication, but the overall font weight looks better then before in my app.

![1716548278793.png](https://github.com/kikipoulet/SukiUI/assets/46953451/79fbd54a-220a-4f45-87d6-1d1c4f094879)

**Comment by AuroraZiling** [comment]
![image](https://github.com/kikipoulet/SukiUI/assets/69903523/df5eab0b-c7a1-409d-be6e-1c60ed08cf84)

- I'm still leaning towards using MiSans, and for the issue of taking up too much space, I'm going to reduce the number of font files introduced to 3 (19mb) or even just 1 (6mb) *`.otf` can slightly reduce the space usage*

- I changed my mind (please help test whether these make sense @yuzh0816 ):
  - Light: `Light`
  - Normal: `Regular`
  - Heavy: `Demibold`

**Comment by AuroraZiling** [comment]
Space usage (3 files):

![image](https://github.com/kikipoulet/SukiUI/assets/69903523/923a4fa3-b39d-4251-bab7-9a104e9581c7)

**Comment by AuroraZiling** [comment]
> > There are only three font variants that are more compatible with SukiUI: Light: `ExtraLight` Normal: `Light` Heavy: `Normal`
> 
> @AuroraZiling  Can I ask you then to just add a simple lightweight (nice) chinese font in the CustomFont folder ? Then I will see an option to use it easily for chinese users, chinese support is a kind of priority as I kind of suspect that almost the majority of the users of the library are chinese friends 👀

After searching for a long time, the fonts that support Chinese are large, MiSans is one of the smaller ones :(

**Comment by kikipoulet** [comment]
> > > There are only three font variants that are more compatible with SukiUI: Light: `ExtraLight` Normal: `Light` Heavy: `Normal`
> > 
> > @AuroraZiling  Can I ask you then to just add a simple lightweight (nice) chinese font in the CustomFont folder ? Then I will see an option to use it easily for chinese users, chinese support is a kind of priority as I kind of suspect that almost the majority of the users of the library are chinese friends 👀
> 
> After searching for a long time, the fonts that support Chinese are large, MiSans is one of the smaller ones :(

Then maybe we can focus on "quality" by including all the MiSans file .. but in another NuGet Package ? 🤔

Like "SukiUI.ChineseFont", so it would stay quite simple. And if one day some UI/UX Chinese specific control is needed, it could be added here too.

**Comment by yuzh0816** [comment]
> > > > There are only three font variants that are more compatible with SukiUI: Light: `ExtraLight` Normal: `Light` Heavy: `Normal`
> > > 
> > > @AuroraZiling  Can I ask you then to just add a simple lightweight (nice) chinese font in the CustomFont folder ? Then I will see an option to use it easily for chinese users, chinese support is a kind of priority as I kind of suspect that almost the majority of the users of the library are chinese friends 👀
> > 
> > After searching for a long time, the fonts that support Chinese are large, MiSans is one of the smaller ones :(
> 
> Then maybe we can focus on "quality" by including all the MiSans file .. but in another NuGet Package ? 🤔
> 
> Like "SukiUI.ChineseFont", so it would stay quite simple. And if one day some UI/UX Chinese specific control is needed, it could be added here too.

Why not try to guide developers HOW to use Chinese fonts in their apps in the documentation? That would be much more easier.✨

**Comment by AuroraZiling** [comment]
I think both can be supported

- Put all MiSans in another Nuget package
- Improve the custom fonts guide in the documentation

**Comment by yuzh0816** [comment]
This issue can be solved by changing the custom font now.
