### ISSUE TITLE
[Feat] MessageBox completion

### ISSUE THREAD

**Issue by AuroraZiling** [kikipoulet/SukiUI#196]
### Check the following items

- [X] I have looked up relevant Issue
- [X] I've read [How To Ask Questions](https://github.com/betaseeker/How-To-Ask-Questions)

### Description of new feature

`MessageBox` doesn't seem to be done yet.

### Package Version

6.0.0-beta6

**Comment by kikipoulet** [comment]
A messageBox feature about :
- a simple API to launch Info/warning/error I suppose
- custom dialog Windows ?
- using the current Dialog system (SukiHost) ?

**Comment by AuroraZiling** [comment]
- yes, and it can be similar to Toast, it is recommended to reuse ToastType (better to change the name, like `NotificationType`) 
- this is necessary, but it is also necessary to provide a simple messagebox to display the text easily.
- how about implement a static method in SukiHost?

**Comment by kikipoulet** [comment]
> - yes, and it can be similar to Toast, it is recommended to reuse ToastType (better to change the name, like `NotificationType`) 
> - this is necessary, but it is also necessary to provide a simple messagebox to display the text easily.
> - how about implement a static method in SukiHost?

To me, we can do it using SukiHost with the current dialog API. The one that doesn't create a new Window but show it animated. 

The use case would be to not create a full control to display a simple info dialog I guess. Besides I have some design ideas for that. 

Is this what you meant ?

**Comment by AuroraZiling** [comment]
yes

**Comment by kikipoulet** [comment]
I think Toast Notifications and MessageBox are related. It's all about giving a feedback + minimal interactivity while being a kind of easy shortcut for the dev, launching one in one line of code. Toast notification being for short message that doesn't need to interrupt the software, and MessageBox for larger piece of text. So I want the two to be kind of close by UI design and API design.

I started by redesigning the toast notifications :

![oknotif](https://github.com/kikipoulet/SukiUI/assets/19242427/08ae1041-dda3-4955-8eb4-e3d19700cd94)

![Peek 25-05-2024 20-10](https://github.com/kikipoulet/SukiUI/assets/19242427/cf1a9e49-b0fb-47d4-afee-f85ecd34821a)


Beside the design changes, there is a new functionality, the "ActionButton". The action toast at the end is called like this : 

```
 SukiHost.ShowToast(new ToastModel("Update Available", 
                             "A new version is available for you.", 
                             ToastType.Info,TimeSpan.FromSeconds(5), null, 
                             "Update Now",  () => { SukiHost.ShowToast("Update", "Update done !");})); 
```

So from this state of toast notification system, I think MessageBox should be used in the exact same way, just to display larger text. I didn't created the API yet in SukiHost for MessageBox, just UI Design model, that I would see it to be like that : 

![Image collée 1](https://github.com/kikipoulet/SukiUI/assets/19242427/a77364f5-5719-4fc8-97b6-2b7a8d5b8039)
![Image collée](https://github.com/kikipoulet/SukiUI/assets/19242427/d8802d3b-ce2d-4d56-b170-7cd91dbb9f0a)

Re-using the same design trend than the toast notification. The "subtle" gradient background for notification and messagebox is key here, as reusing SukiBackground is a little "too much" and give a "same color on same color" effect with the window behind. So to not use a "blank" background, a simple gradient from accent to primary follows the Suki design while not being a dumb copy of bubbly SukiBackground.

I hope it is close from what you had in mind 👀

**Comment by AuroraZiling** [comment]
very nice design. I would like to know if it is possible to customize the content inside MessageBox?

**Comment by kikipoulet** [comment]
It is already possible with the toasts, giving elegant opportunities btw : 

![progressnotif](https://github.com/kikipoulet/SukiUI/assets/19242427/a6fd6fcf-ac1e-4cc9-a116-6177a3fab8b0)

So Messagebox will work the same indeed :+1:

**Comment by kikipoulet** [comment]
with last commit, you can try the new API for messagebox in SukiHost : 

```
SukiHost.ShowMessageBox(new MessageBoxModel(
                        "Update Available", "Lorem ipsum.", 
                        ToastType.Info, "Update Now", () =>{SukiHost.CloseDialog();} ));
  
```
