### ISSUE TITLE
[Bug] GlassCard Animation

### ISSUE THREAD

**Issue by AuroraZiling** [kikipoulet/SukiUI#204]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

the content inside glasscard might resize faster than the animation, and looks strange in some cases

GIF: 

![a](https://github.com/kikipoulet/SukiUI/assets/69903523/6cd6d275-b46a-498a-b93a-f0ed0213bc88)

### Package Version

newest commit

### Environment

Windows 11

### Expected Behavior

content should resize slower or animation should be more faster

### Reproduction

Null

### Additional Information

add a custom property to enable/disable animation is also a solution?

**Comment by kikipoulet** [comment]
👍 

Solved in new last commit, I think it's indeed a good idea to made a "IsAnimated" property, default to true, to at least be able to disable the animations for the Menu and Window part. 

otherswise it gives rich no performance cost interaction everywhere without any effort 

![animation](https://github.com/kikipoulet/SukiUI/assets/19242427/87c5879e-505e-4fd1-8ca2-758fd9312876)
![animation2](https://github.com/kikipoulet/SukiUI/assets/19242427/044387ca-71f2-4301-8c33-21a546c3e5fb)
