### ISSUE TITLE
[Bug] Animation bug on Windows

### ISSUE THREAD

**Issue by yuzh0816** [kikipoulet/SukiUI#212]
### Check the following items

- [x] I have looked up relevant Issue

### Description of the issue

When minimize/maximize the window, it doesn't show the animations as expected.

### Package Version

Latest

### Environment

Windows 11 22635

### Expected Behavior

The application should has animation when minimize/maximize it.

### Reproduction

Just run the application, and you can reproduce the issue.

**Comment by kikipoulet** [comment]
I don't really see the animation you're talking about ..

**Comment by yuzh0816** [comment]
> I don't really see the animation you're talking about ..

In this record, you can see that the window doesn't have a proper animation when maximize it.

https://github.com/kikipoulet/SukiUI/assets/46953451/8a376ff6-257f-4658-bc7a-92fcab8ab0a0

**Comment by AuroraZiling** [comment]
It's indeed a bug

- Current
![noani](https://github.com/kikipoulet/SukiUI/assets/69903523/28b0b520-ba41-4345-9ab2-51feda932479)

- Set `<Setter Property="SystemDecorations" Value="Full" />`
![ani](https://github.com/kikipoulet/SukiUI/assets/69903523/a3ddb67c-f491-4baf-ac07-a92d3b103826)

however, it only animates while maximizing
