### ISSUE TITLE
Unable to resolve type SukiTheme

### ISSUE THREAD

**Issue by MassKlaus** [kikipoulet/SukiUI#213]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

I am trying to use the Suki theme for the first time, I downloaded the 5.3.0 nuget version but it has been unable to revolve the type for the theme, here is the code:
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:sukiUi="clr-namespace:SukiUI;assembly=SukiUI"
             x:Class="OpenSale.UI.App"
             xmlns:local="using:OpenSale.UI"
             RequestedThemeVariant="Default">
             <!-- "Default" ThemeVariant follows system theme variant. "Dark" or "Light" are other available options. -->

    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>

    <Application.Styles>
      <sukiUi:SukiTheme ThemeColor="Blue"/>
    </Application.Styles>
</Application>
```

It gives this error: 
Unable to resolve type SukiTheme from namespace clr-namespace:SukiUI;assembly=SukiUI Line 14, position 8.	OpenSale.UI

### Package Version

5.3.0

### Environment

Windows 10 

### Expected Behavior

Being able to use the theme directly

### Reproduction

using AvaloniaUI 11.0.10 with SukiUI

**Comment by AuroraZiling** [comment]
Avalonia version 11.1.0-beta2 and the latest beta version of SukiUI are recommended.

For version 5.3.0, you may now need to manually checkout to a old commit in order to get the demo at that time.
