### ISSUE TITLE
[Bug] Tooltip does not display when hovering over an object

### ISSUE THREAD

**Issue by niwes** [kikipoulet/SukiUI#219]
### Description of the issue

When setting `ToolTip.Tip` to any object and hovering over that object, the tooltip does not appear. This issue was observed in the SukiUI demo application as well. However, if the main window is not changed to `sukiWindow`, the tooltip works fine. Additionally, this issue occurs with Avalonia version 11.1.0-beta2, but it works correctly with Avalonia version 11.0.11.

### Package Version

6.0.0-beta6

### Environment

Windows 11 22631

### Expected Behavior

The tooltip should appear when hovering over the object.

### Reproduction

1. Clone the SukiUI repository.
2. Open the SukiUI demo application.
3. Set a tooltip.tip to any object (e.g., a button).
4. Run the application.
5. Hover over the object to see if the tooltip appears.

**Comment by sirdoombox** [comment]
I have recreated this issue locally and tried to track down the source of the bug and come up with a potential fix but it evades me.

If you set the `ToolTip.ShowDelay` to `0` the tooltip will appear but flicker very quickly suggesting that something is appearing

Also the tooltips in the top menu items in the demo app work perfectly fine, which is very confusing.
