### ISSUE TITLE
[Bug] Margin on RadioButton.GigaChips:checked Border#SelectedBorder is too large

### ISSUE THREAD

**Issue by nicki419** [kikipoulet/SukiUI#225]
### Check the following items

- [x] I have looked up relevant Issue

### Description of the issue

The Margin on `RadioButton.GigaChips:checked Border#SelectedBorder` of 4 leaves a small ring if one was to change the colour of the border: 
![image](https://github.com/kikipoulet/SukiUI/assets/20019984/e5895748-7944-4cb8-99e5-007343951f83)

### Package Version

6.0.0-beta7

### Environment

Win11, other platforms untested

### Expected Behavior

The above-mentioned small "extra-border" should not be visible. 

### Reproduction

```xml
<Style Selector="RadioButton.GigaChips:checked Border#SelectedBorder">
  <Setter Property="BorderBrush" Value="{DynamicResource SukiBorderBrush}" />
  <Setter Property="BorderThickness" Value="5" />
  <Setter Property="Margin" Value="4" />
</Style>
```

Note: This behaviour does not relate to the BorderThickness Value.

### Additional Information

Original Code as seen in `SukiUI/Theme/RadioButtonStyles.xaml`:

```xml
<Border Name="SelectedBorder"
                            Margin="4"
                            BorderBrush="{DynamicResource SukiPrimaryColor}"
                            BorderThickness="2"
                            CornerRadius="{TemplateBinding CornerRadius}"
                            Opacity="0">
```

Changing the Margin to 3 fixes this issue: 
![image](https://github.com/kikipoulet/SukiUI/assets/20019984/a25abd48-e46e-4a40-b1f7-2367a817c207)

**Comment by AuroraZiling** [comment]
```
<Border Name="SelectedBorder"
                            Margin="4" >>> Margin="3"
                            BorderBrush="{DynamicResource SukiPrimaryColor}"
                            BorderThickness="2"
                            CornerRadius="{TemplateBinding CornerRadius}"
                            Opacity="0">
                        <Border.Transitions>
                            <Transitions>
                                <DoubleTransition Property="Opacity" Duration="0:0:0.2" />
                            </Transitions>
                        </Border.Transitions>
                    </Border>
```

is this right?
