### ISSUE TITLE
[Bug] Unable to use 6.0.0-Beta7 with Avalonia 11.1.0-rc1

### ISSUE THREAD

**Issue by kingnathi112** [kikipoulet/SukiUI#239]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

I have updated the Avalonia package to 11.1.0-rc1 and the app is failing to start.
I get "System.MissingMethodException"

### Package Version

6.0.0-Beta7

### Environment

Windows 11 22631

### Expected Behavior

Able to use SukiUI with the latest Avalonia.

### Reproduction

![2024-07-02_08h58_07](https://github.com/kikipoulet/SukiUI/assets/30069809/31a8ee9b-6b72-4c08-ab5b-2501607afc0f)
Update the Avalonia packages to 11.1.0-rc1 and then try to run the app

**Comment by AuroraZiling** [comment]
wait for next beta
