### ISSUE TITLE
How to pop up in the sub interface

### ISSUE THREAD

**Issue by OaimIsGnay** [kikipoulet/SukiUI#25]
SukiUI.MessageBox.MessageBox.Info(this, "Title", "This is an information message that need to be read.");

<img width="985" alt="image" src="https://user-images.githubusercontent.com/58240619/232428704-04f41bf0-546a-476b-8b7c-0d81c909f1fc.png">

**Comment by kikipoulet** [comment]
Your object MainView is an UserControl object, not a window object

**Comment by OaimIsGnay** [comment]
> Your object MainView is an UserControl object, not a window object

Yes, how should I use it?

**Comment by OaimIsGnay** [comment]
> Your object MainView is an UserControl object, not a window object

user control view unusable? 
Thank you for helping me out
