### ISSUE TITLE
[Bug] Minimize Button Malfunction When Window is Maximized

### ISSUE THREAD

**Issue by Louvest** [kikipoulet/SukiUI#250]
### Check the following items

- [ ] I have looked up relevant Issue

### Description of the issue

When the window is maximized, the minimize button does not function correctly. Upon clicking it, the window briefly disappears and then reappears with a maximization animation.

### Package Version

6.0.0-beta7

### Environment

Windows 10 Pro 22H2 19045.4651

### Expected Behavior

The window should minimize to the taskbar when the minimize button is clicked.

### Reproduction

Open the application.
Maximize the window.
Click the minimize button.

**Comment by kikipoulet** [comment]
fixed in commit fba9d13c9620d535913f3e4227671007057867bd

**Comment by Louvest** [comment]
I checked, this error is in the example from the main branch
