### ISSUE TITLE
[Feat] Native AOT support

### ISSUE THREAD

**Issue by 13584452567** [kikipoulet/SukiUI#253]
### Use the search function to see if this feature has already been suggested.

- [X] I have searched for duplicate issues.

### Description of new feature

the package can be published with <PublishAot>True</PublishAot> and the project sukiui.demo can be published successfully after remove all of x:CompileBindings="True".However it just refuse to start and exit with null output.

### Package Version

6.0.0-beta7

**Comment by kikipoulet** [comment]
NativeAOT is possible with SukiUI https://github.com/kikipoulet/SukiUI/issues/125

The problem with NativeAOT is that it is quite restrictive, especially with code generation, reflection, etc .. Which can be really everywhere. 

I even have an old version of SukiDemo built with NativeAOT, but without all the problematic parts, that you can download here : https://drive.filen.io/d/71b473d1-17c2-4fd4-ba51-cc3a98458503#uaKKtNDPGumDVdKya713h3M54fPIYPL4
