### ISSUE TITLE
mac How to hide the upper left corner 

### ISSUE THREAD

**Issue by OaimIsGnay** [kikipoulet/SukiUI#26]
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/58240619/232988356-6d2bab41-1b63-44fa-a167-4c56ed6a1634.png">

**Comment by kikipoulet** [comment]
I suppose it is more an Avalonia Issue here ..

Moreover, I am not able to test on MacOs

These properties in SukiUI are supposed to hide the native ttile bar : 

`   <Setter Property="ExtendClientAreaToDecorationsHint" Value="True" />
        <Setter Property="ExtendClientAreaChromeHints" Value="NoChrome" />
        <Setter Property="ExtendClientAreaTitleBarHeightHint" Value="-1" />`

Works on Windows & Linux

**Comment by OaimIsGnay** [comment]
> I suppose it is more an Avalonia Issue here ..
> 
> Moreover, I am not able to test on MacOs
> 
> These properties in SukiUI are supposed to hide the native ttile bar :
> 
> ` <Setter Property="ExtendClientAreaToDecorationsHint" Value="True" /> <Setter Property="ExtendClientAreaChromeHints" Value="NoChrome" /> <Setter Property="ExtendClientAreaTitleBarHeightHint" Value="-1" />`
> 
> Works on Windows & Linux

I added this Classes="NakedWindow" 

And what you said
<img width="663" alt="image" src="https://user-images.githubusercontent.com/58240619/233522268-eb585b21-eafa-4280-bd4e-38be2e9ab620.png">

Solved the problem thank you
