### ISSUE TITLE
May I ask if there is a way to know which menu item was clicked on

### ISSUE THREAD

**Issue by OaimIsGnay** [kikipoulet/SukiUI#27]
<img width="140" alt="image" src="https://user-images.githubusercontent.com/58240619/233825192-99968e12-f3c7-4492-a447-95104f200964.png">

I want to know if I clicked on the user menu, or library.
I want to match with the region of Prism

**Comment by kikipoulet** [comment]
Not right now, could be done later

**Comment by OaimIsGnay** [comment]
> Not right now, could be done later

Do you have a plan? please

**Comment by OaimIsGnay** [comment]
> Not right now, could be done later

I am looking forward to this feature

**Comment by kikipoulet** [comment]
I don't write code on my spare time to have deadlines so I have no 'plan'

But I added the idea in my todo list in my notes app at the deepest point of my phone, that's the best I can offer :)

**Comment by OaimIsGnay** [comment]
> I don't write code on my spare time to have deadlines so I have no 'plan'
> 
> But I added the idea in my todo list in my notes app at the deepest point of my phone, that's the best I can offer :)

Cool, thank you

I am looking forward to it

**Comment by kikipoulet** [comment]
In new nuget package 4.7.1, there is a "MenuItemChanged" event in the SIdeMenu that is triggered everytime the MenuItem change, the event has the header string has argument
