### ISSUE TITLE
[Bug] There is no "SukiWindow" class in namespace SukiUI.Controls

### ISSUE THREAD

**Issue by FeJQ** [kikipoulet/SukiUI#276]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

Avalonia => 11.1.0
SukiUI => 5.3.0
![image](https://github.com/user-attachments/assets/388e0de5-1789-489b-ae27-570a58530a05)

### Package Version

5.3.0

### Environment

Windows 11 23H2 (22631.4037)

### Expected Behavior

Make a hello world example

### Reproduction

Always

**Comment by AuroraZiling** [comment]
try SukiUI beta version
