### ISSUE TITLE
ComboBoxItem not resizable

### ISSUE THREAD

**Issue by montex12** [kikipoulet/SukiUI#28]
Hello,

After applying SukiUI theme to my app the ComboBox items popup seems to have a fixed size and is not resizable.
I am placing the ComboBox in a PanAndZoom.ZoomBorder which seems to resize all controls except the ComboBox items popup.

Is there anything that force the ComboBox to have that fixed size?

**Comment by kikipoulet** [comment]
Can you show me the problem with a screenshot ? I don't really visualize the problem

**Comment by kikipoulet** [comment]
I don't know if it is because of sukiui because when deleting the Combobox style it still happens 

![image](https://github.com/kikipoulet/SukiUI/assets/19242427/f9d9d48c-50de-4c8b-9010-1d2fc1577ce6)
