### ISSUE TITLE
Sponsorship 

### ISSUE THREAD

**Issue by andrewmd5** [kikipoulet/SukiUI#284]
### Use the search function to see if this feature has already been suggested.

- [X] I have searched for duplicate issues.

### Description of new feature

Hey there —

I’m using Suki in [my app](https://dolus.app/) and I was curious how to sponsor the project as I couldn’t find any links to donate.

### Package Version

6.0.0

**Comment by kikipoulet** [comment]
Hi,


There is no need for donations don't worry. But thank you very much for thinking about it, in fact it's even more meaningful than a donation itself, I'm glad you appreciate the work here.

Congratulations for the release of your app, I like what you have done with the library to make it more personal, it is very nice.
