### ISSUE TITLE
[Feat] SideMenu ReactiveUI

### ISSUE THREAD

**Issue by imabdul-dev** [kikipoulet/SukiUI#287]
### Use the search function to see if this feature has already been suggested.

- [X] I have searched for duplicate issues.

### Description of new feature

Please add support of SideMenu content display support with ReactiveUI. See the example below,
`<reactiveUi:RoutedViewHost Router="{Binding Router}"/>`

### Package Version

6.0.0-beta8

**Comment by kikipoulet** [comment]
Right now we are focused on releasing the final 6.0.0 version, so I think we won't do it soon at all, but I keep it as a suggestion.

Otherwise, PR are welcomed if you feel courageous enough to do it 👍
