### ISSUE TITLE
[Doc] How to use SukiSideMenu.ItemsSource and SukiSideMenu.SelectedItem?

### ISSUE THREAD

**Issue by KaranocaVe** [kikipoulet/SukiUI#289]
### Suggestion

I'm a beginner for AvaloniaUI based on MVVM. I'm trying to implement side menu function in my app following the example in document. This is my code`    <sukiUi:SukiSideMenu IsSearchEnabled="True" ItemsSource="{Binding MenuItems}" SelectedItem="{Binding SelectedPage}">
        <sukiUi:SukiSideMenu.ItemTemplate>
            <DataTemplate>
                <sukiUi:SukiSideMenuItem Classes="Compact" Header="{Binding DisplayName}" PageContent="{Binding PageCont}">
                </sukiUi:SukiSideMenuItem>
            </DataTemplate>
        </sukiUi:SukiSideMenu.ItemTemplate>
    </sukiUi:SukiSideMenu>
`
`namespace WikiPhoto.ViewModels
{

    public class MainWindowViewModel : ViewModelBase
    {

        public ObservableCollection<MenuItem> MenuItems { get; } = new()
        {
            new()
            {
                DisplayName = "Photo",
                PageCont = new PhotoView()
            },
            new()
            {
                DisplayName = "About",
                PageCont = new AboutView()
            }
        };

        public class MenuItem
        {
            public string DisplayName { get; set; }
            public UserControl PageCont { get; set; }
        }

        private ObservableCollection<string> _photo = new();

        public ObservableCollection<string> Photo
        {
            get => _photo;
            set
            {
                this.RaiseAndSetIfChanged(ref _photo, value);
            }
        }

        private MenuItem _selectedPage;
        
        public MenuItem SelectedPage
        {
            get => _selectedPage;
            set
            {
                this.RaiseAndSetIfChanged(ref _selectedPage, value);
                Console.WriteLine($"{SystemClock.UtcNow.Second}");
            }
        }
        
        public MainWindowViewModel()
        {
            Photo.Add("111111");
            SelectedPage = MenuItems[1];
        }
    }
}`

Obviously it doesn't work. But when I read SukiUI.demo's implementation which is mentioned in the document, I felled puzzled, why the ItemSource is a collection of viewmodels? And how the navigation service works?

**Comment by KaranocaVe** [comment]
OK, I have read the source code and changed to `        private ObservableCollection<SukiSideMenuItem> _menuItems;`, then it works

**Comment by zkxjzmswkwl** [comment]
New to Avalonia. Don't know C#. 

Why does that work? Seems black-boxy and suggests documentation could use a touch-up.

**Comment by AuroraZiling** [comment]
The Demo implementation uses [DI](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection), making it easy to handle changes in the number of pages through [reflection](https://github.com/kikipoulet/SukiUI/blob/da9b61cdbfef9b917581710276d589906996b78a/SukiUI.Demo/App.axaml.cs#L60), which is mainly for managing multiple instances of Views. 

You can also set up your own 'bindings' to Views (like DataContext or ViewLocator) and ViewModels. However, these implementations are beyond the scope of this documentation.

**Comment by cditqq** [comment]
The binding of PageContent is not taking effect. I don't know what's going on

`
<suki:SukiSideMenu IsSearchEnabled="False"
             SearchText="{Binding SearchContent}"
             ItemsSource="{Binding MenuItems}">
  <suki:SukiSideMenu.ItemTemplate>
      <DataTemplate>
           <suki:SukiSideMenuItem Classes="Compact" Header="{Binding Header}"   IsExpanded="{Binding IsExpanded}" PageContent="{Binding PageContent}"> </suki:SukiSideMenuItem>
      </DataTemplate>
    </suki:SukiSideMenu.ItemTemplate>
 </suki:SukiSideMenu>
   
`
`
MenuItems = new ObservableCollection<MenuItemModel>
{
    new MenuItemModel
    {
        Header = HomePageContent,
        IconKind = "MonitorDashboard",
        PageContent = new DashboardView() 
    }
}
`
`
 public partial class MenuItemModel : ObservableObject
 {
     [ObservableProperty] private string header;
     [ObservableProperty] private string iconKind;
     [ObservableProperty] private UserControl pageContent;
     [ObservableProperty] private bool isVisible = true; 
     [ObservableProperty] private bool isExpanded = true; 

     [ObservableProperty] private ObservableCollection<MenuItemModel> items = new ObservableCollection<MenuItemModel>() { };
 }
`

**Comment by cditqq** [comment]
The binding of PageContent is not taking effect. I don't know what's going on

```
<suki:SukiSideMenu IsSearchEnabled="False"
             SearchText="{Binding SearchContent}"
             ItemsSource="{Binding MenuItems}">
  <suki:SukiSideMenu.ItemTemplate>
      <DataTemplate>
           <suki:SukiSideMenuItem Classes="Compact" Header="{Binding Header}"   IsExpanded="{Binding IsExpanded}" PageContent="{Binding PageContent}"> </suki:SukiSideMenuItem>
      </DataTemplate>
    </suki:SukiSideMenu.ItemTemplate>
 </suki:SukiSideMenu>
```

```
MenuItems = new ObservableCollection<MenuItemModel>
{
    new MenuItemModel
    {
        Header = HomePageContent,
        IconKind = "MonitorDashboard",
        PageContent = new DashboardView() 
    }
}
```


```
 public partial class MenuItemModel : ObservableObject
 {
     [ObservableProperty] private string header;
     [ObservableProperty] private string iconKind;
     [ObservableProperty] private UserControl pageContent;
     [ObservableProperty] private bool isVisible = true; 
     [ObservableProperty] private bool isExpanded = true; 
     [ObservableProperty] private ObservableCollection<MenuItemModel> items = new ObservableCollection<MenuItemModel>() { };
 }
```

**Comment by KaranocaVe** [comment]
> PageContent的绑定不生效。我不知道发生了什么。视图未显示
> 
> ```
> <suki:SukiSideMenu IsSearchEnabled="False"
>              SearchText="{Binding SearchContent}"
>              ItemsSource="{Binding MenuItems}">
>   <suki:SukiSideMenu.ItemTemplate>
>       <DataTemplate>
>            <suki:SukiSideMenuItem Classes="Compact" Header="{Binding Header}"   IsExpanded="{Binding IsExpanded}" PageContent="{Binding PageContent}"> </suki:SukiSideMenuItem>
>       </DataTemplate>
>     </suki:SukiSideMenu.ItemTemplate>
>  </suki:SukiSideMenu>
> ```
> 
> ```
> MenuItems = new ObservableCollection<MenuItemModel>
> {
>     new MenuItemModel
>     {
>         Header = HomePageContent,
>         IconKind = "MonitorDashboard",
>         PageContent = new DashboardView() 
>     }
> }
> ```
> 
> ```
>  public partial class MenuItemModel : ObservableObject
>  {
>      [ObservableProperty] private string header;
>      [ObservableProperty] private string iconKind;
>      [ObservableProperty] private UserControl pageContent;
>      [ObservableProperty] private bool isVisible = true; 
>      [ObservableProperty] private bool isExpanded = true; 
>      [ObservableProperty] private ObservableCollection<MenuItemModel> items = new ObservableCollection<MenuItemModel>() { };
>  }
> ```

Why extend from ObservableObject rather than something to do with MenuItem？
SukiUI have no clues to know it’s a MenuItem.

**Comment by cditqq** [comment]
ViewModelBase also inherits from ObservableObject
The menu is displayed, but the PageContent view is not showing

**Comment by KaranocaVe** [comment]
> <img alt="Image" width="677" height="318" src="https://private-user-images.githubusercontent.com/48109887/470594963-9cac2ac1-2187-4d5b-8bda-c1e63f390cb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MTA2OTksIm5iZiI6MTc1MzQxMDM5OSwicGF0aCI6Ii80ODEwOTg4Ny80NzA1OTQ5NjMtOWNhYzJhYzEtMjE4Ny00ZDViLThiZGEtYzFlNjNmMzkwY2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI1VDAyMjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNWYzZjJhY2M1MzYwNDE3MzE3MDBhNDAzMjBjY2M2OTNlZDhiYzVhODAwMjcxMWZhNDk2YzZkNGU2YWQwN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qLHbWYXi2faamFRoCYa1J2LokQ22h1dTPF37MlZpriM"> <img alt="Image" width="1213" height="193" src="https://private-user-images.githubusercontent.com/48109887/470595015-a9413e24-68c7-4131-a904-231f15603e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MTA2OTksIm5iZiI6MTc1MzQxMDM5OSwicGF0aCI6Ii80ODEwOTg4Ny80NzA1OTUwMTUtYTk0MTNlMjQtNjhjNy00MTMxLWE5MDQtMjMxZjE1NjAzZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI1VDAyMjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNjY1ODQ2ZGU2YzQyNGQ0M2EzZGI1ZDJjOGJjNzIwZTQ0ZGIzMGQ2NGE3YzBkZDI4NGFmZmNiZjgwODcxNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1njP0fEGrIOjxCd_GvUR3VLGKyEGUYhtsA1XCppOl4I">

This is exactly the same as the problem I encountered before. sukiui failed to correctly identify your page.

**Comment by KaranocaVe** [comment]
> <img alt="Image" width="677" height="318" src="https://private-user-images.githubusercontent.com/48109887/470594963-9cac2ac1-2187-4d5b-8bda-c1e63f390cb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MTI3NjksIm5iZiI6MTc1MzQxMjQ2OSwicGF0aCI6Ii80ODEwOTg4Ny80NzA1OTQ5NjMtOWNhYzJhYzEtMjE4Ny00ZDViLThiZGEtYzFlNjNmMzkwY2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI1VDAzMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMzUzMTIwMTI4NmI5Yzg3YTZjOWRiMjkxZDY3MWY0NWY3ZWYwMTE0ODA5MTRkZDljNDBmMmM2NzYzNWViNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GG1SbG-Z6ykWMxHHmc_UoG_xSKX6i4XU3ENM2qzuj5A"> <img alt="Image" width="1213" height="193" src="https://private-user-images.githubusercontent.com/48109887/470595015-a9413e24-68c7-4131-a904-231f15603e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MTI3NjksIm5iZiI6MTc1MzQxMjQ2OSwicGF0aCI6Ii80ODEwOTg4Ny80NzA1OTUwMTUtYTk0MTNlMjQtNjhjNy00MTMxLWE5MDQtMjMxZjE1NjAzZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI1VDAzMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTVkZjVlODVmZDAzOWM3MDY5ZjZlMDc2ODc2MGRiZDE1YmUxNGUxNjI4Mjk1NjM0NGUxYWYyMGZkNDliOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B8Ov74HapIBxRNh-3M5Fjfcd7zKUmQ3CPJtsL4CabSA">

here is the code
`using System.Collections.ObjectModel;
using Avalonia.Controls;
using CommunityToolkit.Mvvm.ComponentModel;
using SukiUI.Controls;

namespace AvaloniaApplication1.ViewModels;

public partial class MainWindowViewModel : ViewModelBase
{
    public partial class MenuItemModel : SukiSideMenuItem
    {
        private string header = string.Empty;
        private string iconKind = string.Empty;
        private ContentControl pageContent = new ContentControl();
        private bool isVisible = true;
         private bool isExpanded = true;
    }

    public ObservableCollection<MenuItemModel> MenuItems { get; } = new ObservableCollection<MenuItemModel>
    {
        new()
        {
            Header = "测试主页", // 更改 Header 更具描述性
            PageContent = new UserControl // 直接在这里构造 UserControl 的内容
            {
                Content = new TextBlock
                {
                    Text = "你好，这是在 ViewModel 中直接创建的文本内容！",
                    HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center,
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                    FontSize = 20,
                    Margin = new Avalonia.Thickness(20)
                }
            }
        },
        new()
        {
            Header = "另一个测试页面",
            PageContent = new UserControl
            {
                Content = new StackPanel
                {
                    Margin = new Avalonia.Thickness(15),
                    Children =
                    {
                        new TextBlock { Text = "这是另一个页面的标题", FontSize = 18, FontWeight = Avalonia.Media.FontWeight.Bold },
                        new TextBlock { Text = "这里可以放更多代码创建的控件。", Margin = new Avalonia.Thickness(0, 10, 0, 0) }
                    }
                }
            }
        }
    };
}`

**Comment by cditqq** [comment]
Thank you very much for your help. Following your solution, after inheriting SukiSideMenuItem, the view is displayed, but the menu cannot be shown, or some additional properties are not displayed. Do you have any solutions for this?

**Comment by cditqq** [comment]
Thank you again. Currently, I am doing just that, using SukiSideMenuItem directly. Is there a way to solve the issue with the icon?

**Comment by KaranocaVe** [comment]
> Thank you again. Currently, I am doing just that, using SukiSideMenuItem directly. Is there a way to solve the issue with the icon?

Which kind of icon are you using?
You may google “how to use icons in AvaloniaUI”?
The icon here is just icon.

**Comment by KaranocaVe** [comment]
> > The Demo implementation uses [DI](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection), making it easy to handle changes in the number of pages through [reflection](https://github.com/kikipoulet/SukiUI/blob/da9b61cdbfef9b917581710276d589906996b78a/SukiUI.Demo/App.axaml.cs#L60), which is mainly for managing multiple instances of Views.
> > You can also set up your own 'bindings' to Views (like DataContext or ViewLocator) and ViewModels. However, these implementations are beyond the scope of this documentation.
> 
> Just seeing this. DI libraries are a comically stupid idea that somehow has gripped C# developers, but that's besides the point here.
> 
> Demos should plainly show use cases. Introducing implicit behavior via vendored packages in the foundation of a demo makes zero sense.

Maybe some Java developer get fired and then decide to do something with .NET

**Comment by ZGdadong** [comment]
> > The Demo implementation uses [DI](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection), making it easy to handle changes in the number of pages through [reflection](https://github.com/kikipoulet/SukiUI/blob/da9b61cdbfef9b917581710276d589906996b78a/SukiUI.Demo/App.axaml.cs#L60), which is mainly for managing multiple instances of Views.Demo 实现使用 [DI，](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection) 通过[反射](https://github.com/kikipoulet/SukiUI/blob/da9b61cdbfef9b917581710276d589906996b78a/SukiUI.Demo/App.axaml.cs#L60)可以轻松处理页数的变化，这主要用于管理 View 的多个实例。
> > You can also set up your own 'bindings' to Views (like DataContext or ViewLocator) and ViewModels. However, these implementations are beyond the scope of this documentation.您还可以设置自己的视图（如 DataContext 或 ViewLocator）和 ViewModel 的“绑定”。但是，这些实现超出了本文档的范围。
> 
> Just seeing this. DI libraries are a comically stupid idea that somehow has gripped C# developers, but that's besides the point here.只是看到这个。DI 库是一个滑稽的愚蠢想法，不知何故吸引了 C# 开发人员，但这不是这里的重点。
> 
> Demos should plainly show use cases. Introducing implicit behavior via vendored packages in the foundation of a demo makes zero sense.演示应该清楚地展示用例。在演示的基础上通过供应商包引入隐式行为是毫无意义的。

Yes, you're right.Besides this, there is another place in the demo that uses this SukiSideMenu.It is Dashboard.

<img width="1920" height="1117" alt="Image" src="https://github.com/user-attachments/assets/a3e05d15-15c0-43f4-bb70-ebcd1741635e" />
But the code isn't complete

<img width="839" height="594" alt="Image" src="https://github.com/user-attachments/assets/c137ab1c-7982-49de-90ed-73a3b50c04db" />
So developers should improve the cases under the Dashboard

**Comment by ZGdadong** [comment]
<img width="1920" height="1117" alt="Image" src="https://github.com/user-attachments/assets/61802f54-0655-4db2-a440-8b79897ff6f5" />

**Comment by kikipoulet** [comment]
> > > The Demo implementation uses [DI](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection), making it easy to handle changes in the number of pages through [reflection](https://github.com/kikipoulet/SukiUI/blob/da9b61cdbfef9b917581710276d589906996b78a/SukiUI.Demo/App.axaml.cs#L60), which is mainly for managing multiple instances of Views.Demo 实现使用 [DI，](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection) 通过[反射](https://github.com/kikipoulet/SukiUI/blob/da9b61cdbfef9b917581710276d589906996b78a/SukiUI.Demo/App.axaml.cs#L60)可以轻松处理页数的变化，这主要用于管理 View 的多个实例。
> > > You can also set up your own 'bindings' to Views (like DataContext or ViewLocator) and ViewModels. However, these implementations are beyond the scope of this documentation.您还可以设置自己的视图（如 DataContext 或 ViewLocator）和 ViewModel 的“绑定”。但是，这些实现超出了本文档的范围。
> > 
> > Just seeing this. DI libraries are a comically stupid idea that somehow has gripped C# developers, but that's besides the point here.只是看到这个。DI 库是一个滑稽的愚蠢想法，不知何故吸引了 C# 开发人员，但这不是这里的重点。
> > 
> > Demos should plainly show use cases. Introducing implicit behavior via vendored packages in the foundation of a demo makes zero sense.演示应该清楚地展示用例。在演示的基础上通过供应商包引入隐式行为是毫无意义的。
> 
> Yes, you're right.Besides this, there is another place in the demo that uses this SukiSideMenu.It is Dashboard.
> 
> <img width="1920" height="1117" alt="Image" src="https://github.com/user-attachments/assets/a3e05d15-15c0-43f4-bb70-ebcd1741635e" />
> But the code isn't complete
> 
> <img width="839" height="594" alt="Image" src="https://github.com/user-attachments/assets/c137ab1c-7982-49de-90ed-73a3b50c04db" />
> So developers should improve the cases under the Dashboard
> 

Dude, if it bothers you enough to make 3 annoted screenshots, why not make a PR instead ? 

Isn't it what Open-Source is for ?
