### ISSUE TITLE
[Bug] UI components unintended refresh behavior

### ISSUE THREAD

**Issue by 13584452567** [kikipoulet/SukiUI#290]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

https://github.com/user-attachments/assets/91c6fbd6-3b37-46d3-a653-1fdc3fc28292

ToggleSwitch refresh unexpectedly

### Package Version

6.0.0-beta8

### Environment

Windows 11 26100.1742

### Expected Behavior

just appear，without refresh

### Reproduction

just click this UI component

**Comment by kikipoulet** [comment]
It is this part in the ToggleSwitch style file  : 

![{D73E3904-0D2F-4113-9E3A-97C623B3327D}](https://github.com/user-attachments/assets/3b6cf45e-f100-4e7b-9656-6c557ecfe584)

the checked and unchecked part. I've already looked a little, I tried different Fillmode, but it just seems that its existence trigger that which is super annoying.

**Comment by 13584452567** [comment]
is it an avalonia's ploblem?

**Comment by kikipoulet** [comment]
> is it an avalonia's ploblem?

I don't know, maybe there's something I missed. I'm going to take another look soon

**Comment by kikipoulet** [comment]
Modified animations to transitions, it's a little less sweet now but the issue is fixed
