### ISSUE TITLE
The Notification doesn't seem to be working; you have to click twice to get the message to pop up properly.

### ISSUE THREAD

**Issue by wj8400684** [kikipoulet/SukiUI#30]

**Comment by kikipoulet** [comment]
The "click twice" seems to be an Avalonia thing as it did it when I remove the styles.
Or maybe the SukiTest project that don't use the notification correctly.

Anyway, there were strange things : 
- animation was occuring two times with a weird horrible visual result
- Dark theme was not updated

I fixed this in the last commit

**Comment by wj8400684** [comment]
Can we fix this?

**Comment by kikipoulet** [comment]
You can test notifications in an Avalonia preview8 project without SukiUI to see if it does it too

**Comment by wj8400684** [comment]
<img width="1339" alt="image" src="https://github.com/kikipoulet/SukiUI/assets/39239954/07b4aa61-a483-4dce-bdef-bc4cf77393ae">
This project is also based on preview8.0 and the notification component is working fine! You can check it out。
https://github.com/irihitech/Semi.Avalonia.git
