### ISSUE TITLE
[Bug] AOT problem: 1. Program will crash if use SukiSideMenu. 2. Program will crash if use SukiWindow when run in win7.

### ISSUE THREAD

**Issue by telesa864** [kikipoulet/SukiUI#308]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

AOT is success, but run with crash.
1. Program will crash if use SukiSideMenu. 
2. Program will crash if use SukiWindow when run in win7.

### Package Version

6.0.0.-beta8

### Environment

win7 or win11

### Expected Behavior

.

### Reproduction

.

**Comment by kikipoulet** [comment]
What code ? The SukiDemo project doesn't work with AOT because of using a ViewLocator.

**Comment by telesa864** [comment]
> What code ? The SukiDemo project doesn't work with AOT because of using a ViewLocator.

My test project without ViewLocator.
![屏幕截图 2024-10-14 164034](https://github.com/user-attachments/assets/dca8fdb6-4c45-4ee8-ab2c-cad359d0e3b5)

**Comment by telesa864** [comment]
By the way, when the window is maximized, the icon after the side menu is collapsed is not centered.
![Uploading 屏幕截图 2024-10-14 164854.png…]()
