### ISSUE TITLE
[Bug] Following the installation guide results in a crash at runtime

### ISSUE THREAD

**Issue by danieljfarrell** [kikipoulet/SukiUI#318]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

Suki looks amazing, I'm really excited to try it out.

I have followed the steps in the installation guide, https://kikipoulet.github.io/SukiUI/documentation/getting-started/installation.html

This results in a project the builds fine but crashes at runtime.

    System.TypeLoadException: 'Method 'CreateEmbeddableTopLevel' in type 'Avalonia.Win32.Win32Platform' from assembly 'Avalonia.Win32, Version=11.0.6.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b' does not have an implementation.'

<img width="1194" alt="Screenshot 2024-10-29 at 13 22 39" src="https://github.com/user-attachments/assets/50686f87-db17-4289-8991-15a9c15c6cf3">

<img width="793" alt="image" src="https://github.com/user-attachments/assets/d5441f47-c513-4c84-887f-6f83e3b5d63d">

Following the guide, I am using Suki 6.0.0-beta6 and Avalonia 11.2.0-beta1. Here is the bare project if that is helpful, https://github.com/danieljfarrell/SukiDemoApp

### Package Version

6.0.0-beta6

### Environment

Windows 11 ARM

### Expected Behavior

I'm never sure what to write in the expected behaviour box without sounding flippant.

### Reproduction

Yes, this is totally reproducible.

**Comment by hisaner** [comment]
I have a similar issue at this error location，use lastest avalonia11.2.0rc2 and suki 6.0rc
System.InvalidOperationException
  HResult=0x80131509
  Message=Control 'MainView' is a top level control and cannot be added as a child.
  Source=Avalonia.Controls
  StackTrace:
   在 Avalonia.Controls.TopLevel.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e)
   在 Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   在 Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   在 Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   在 Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   在 Avalonia.Visual.SetVisualParent(Visual value)
   在 Avalonia.Visual.SetVisualParent(IList children, Visual parent)
   在 Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   在 Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   在 Avalonia.Collections.AvaloniaList`1.Add(T item)
   在 Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content)
   在 Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   在 Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate()
   在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   在 Avalonia.Layout.Layoutable.Measure(Size availableSize)
   在 Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding)
   在 Avalonia.Controls.Decorator.MeasureOverride(Size availableSize)
   在 Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
   在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   在 Avalonia.Layout.Layoutable.Measure(Size availableSize)
   在 Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   在 Avalonia.Layout.Layoutable.Measure(Size availableSize)
   在 Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   在 Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   在 Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   在 Avalonia.Layout.Layoutable.Measure(Size availableSize)
   在 Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   在 Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   在 Avalonia.Controls.Window.ShowCore(Window owner)
   在 Avalonia.Controls.Window.Show()
   在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow()
   在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   在 Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   在 Lottery.Desktop.Program.Main(String[] args) 在 D:\Source\Lottery\Lottery.Desktop\Program.cs 中: 第 13 行

**Comment by kikipoulet** [comment]
> I have a similar issue at this error location，use lastest avalonia11.2.0rc2 and suki 6.0rc System.InvalidOperationException HResult=0x80131509 Message=Control 'MainView' is a top level control and cannot be added as a child. Source=Avalonia.Controls StackTrace: 在 Avalonia.Controls.TopLevel.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) 在 Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Visual.SetVisualParent(Visual value) 在 Avalonia.Visual.SetVisualParent(IList children, Visual parent) 在 Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) 在 Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) 在 Avalonia.Collections.AvaloniaList`1.Add(T item) 在 Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content) 在 Avalonia.Controls.Presenters.ContentPresenter.UpdateChild() 在 Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate() 在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding) 在 Avalonia.Controls.Decorator.MeasureOverride(Size availableSize) 在 Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) 在 Avalonia.Controls.Window.MeasureOverride(Size availableSize) 在 Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.LayoutManager.Measure(Layoutable control) 在 Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() 在 Avalonia.Controls.Window.ShowCore(Window owner) 在 Avalonia.Controls.Window.Show() 在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() 在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args) 在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) 在 Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder) 在 Lottery.Desktop.Program.Main(String[] args) 在 D:\Source\Lottery\Lottery.Desktop\Program.cs 中: 第 13 行

It seems to be an error in your code. Are you using a xplat project and using SukiWindow in your MainView instead of MainWindow for example ?

**Comment by hisaner** [comment]
> > I have a similar issue at this error location，use lastest avalonia11.2.0rc2 and suki 6.0rc System.InvalidOperationException HResult=0x80131509 Message=Control 'MainView' is a top level control and cannot be added as a child. Source=Avalonia.Controls StackTrace: 在 Avalonia.Controls.TopLevel.OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) 在 Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Layout.Layoutable.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Input.InputElement.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e) 在 Avalonia.Visual.SetVisualParent(Visual value) 在 Avalonia.Visual.SetVisualParent(IList children, Visual parent) 在 Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) 在 Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) 在 Avalonia.Collections.AvaloniaList`1.Add(T item) 在 Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content) 在 Avalonia.Controls.Presenters.ContentPresenter.UpdateChild() 在 Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate() 在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding) 在 Avalonia.Controls.Decorator.MeasureOverride(Size availableSize) 在 Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) 在 Avalonia.Controls.Window.MeasureOverride(Size availableSize) 在 Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) 在 Avalonia.Layout.Layoutable.Measure(Size availableSize) 在 Avalonia.Layout.LayoutManager.Measure(Layoutable control) 在 Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() 在 Avalonia.Controls.Window.ShowCore(Window owner) 在 Avalonia.Controls.Window.Show() 在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() 在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args) 在 Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) 在 Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder) 在 Lottery.Desktop.Program.Main(String[] args) 在 D:\Source\Lottery\Lottery.Desktop\Program.cs 中: 第 13 行
> 
> It seems to be an error in your code. Are you using a xplat project and using SukiWindow in your MainView instead of MainWindow for example ?

I only used the Avalonia MVVM cross platform template and the MVVM toolkit，and replaced UserControl with SukiWindow

**Comment by sirdoombox** [comment]
You should only replace `Window` with `SukiWindow`.

Replacing `UserControl` with `SukiWindow` and then trying to place that inside another window will cause a crash.

`MainView` should be a `UserControl` and only `MainWindow` should be `SukiWindow`

**Comment by danieljfarrell** [comment]
> So update all your Avalonia packages, and I advice you to use suki 6.0.0-rc by the way 👍

Yes! This was all that was needed. 

<img width="353" alt="image" src="https://github.com/user-attachments/assets/2eea1f66-783c-4af1-9d3b-49aaa4ab6c7b">

Thanks :)
