### ISSUE TITLE
[Bug] DataGrid: Header and Table Grid Lines Misalignment with CanUserResizeColumns and GridLinesVisibility

### ISSUE THREAD

**Issue by Louvest** [kikipoulet/SukiUI#319]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

When enabling `CanUserResizeColumns="True"` and `GridLinesVisibility="All"` in DataGrid, grid lines in the header (created by CanUserResizeColumns) and in the table (created by GridLinesVisibility) are misaligned. The line color in the table differs from that in the header, and the table lines are offset slightly to the right compared to the header lines.

### Package Version

6.0.0-rc

### Environment

Windows 10 

### Expected Behavior

Grid lines in the header and the table should match in color and alignment.

### Reproduction

1. Set up a DataGrid in Avalonia.
2. Enable CanUserResizeColumns="True" and GridLinesVisibility="All".

### Additional Information

![image](https://github.com/user-attachments/assets/55971c60-ab66-4b7d-b225-1874901630fd)

**Comment by kikipoulet** [comment]
We won't support extensively the DataGrid control for various reason, but I at least modified the style to have this alternative style when using "GridLinesVisibility" to All.

![{1EF9F891-D3D3-48CA-A40B-EAA873D3FA9F}](https://github.com/user-attachments/assets/93a0a591-c350-49a0-b36f-20f4580a3a94)
