### ISSUE TITLE
Can add a style to the Notification?

### ISSUE THREAD

**Issue by wj8400684** [kikipoulet/SukiUI#32]
<img width="313" alt="image" src="https://github.com/kikipoulet/SukiUI/assets/39239954/703b0a19-d87c-4822-a06f-7ef3c7875a05">
like this!

**Comment by kikipoulet** [comment]
aaaarrghh you like notifications, don't you ?
only thing missing in sukiui is the icon, which is not a bad idea to be honest

**Comment by wj8400684** [comment]
Thank you🙏！
