### ISSUE TITLE
[Feat] Will there be support for the theme of the TreeDataGrid control?

### ISSUE THREAD

**Issue by vm0100** [kikipoulet/SukiUI#320]
### Use the search function to see if this feature has already been suggested.

- [X] I have searched for duplicate issues.

### Description of new feature

Will there be support for the theme of the TreeDataGrid control? The DataGrid control does not support single operations, while TreeDataGrid supports more configurations. 

For example: https://docs.avaloniaui.net/zh-Hans/docs/reference/controls/treedatagrid/

### Package Version

6.0.0-beta8

**Comment by sirdoombox** [comment]
From my perspective it's hard to justify maintaining support for `TreeDataGrid` as Avalonia barely supports it themselves.

It has numerous bugs and issues, receives little to no meaningful improvements and was primarily designed as a paid product which they didn't end up selling. I don't think it's a very good control and honestly I don't see that it's worth us having to maintain an entirely new project within SukiUI to support it.
