### ISSUE TITLE
[Doc] How can I run the demo app locally?

### ISSUE THREAD

**Issue by danieljfarrell** [kikipoulet/SukiUI#321]
### Suggestion

I followed the link to the microsoft store to try the demo application which cannot be found

<img width="747" alt="image" src="https://github.com/user-attachments/assets/96bafe64-4296-46cc-ac25-f2d5735c3dd3">

But no problem, it will actually be better to run the application for source so I can see how things are done. I am not that familiar with visual studio, how do I run the demo application? The usual way I do things does not seem to work.

<img width="485" alt="Screenshot 2024-11-01 at 07 08 47" src="https://github.com/user-attachments/assets/51aeff53-6320-4adf-9b37-9c565f04941f">

<img width="462" alt="Screenshot 2024-11-01 at 07 08 56" src="https://github.com/user-attachments/assets/23cd937b-6380-4790-bce2-3c8bfb9f4779">

**Comment by Insire** [comment]
You have to actually start the demo application and not the library. See this for reference: 
![grafik](https://github.com/user-attachments/assets/9d196a9a-f1c2-469b-afa5-5d1d3932dfb2)

**Comment by danieljfarrell** [comment]
Thank you! Sorry to bother you with basic questions but you answer is appreciated!
