### ISSUE TITLE
[Bug] Latest Dock.Avalonia 11.2.0 does not work with latest SukiUI.Dock 

### ISSUE THREAD

**Issue by stevenswan** [kikipoulet/SukiUI#332]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

When trying to use Dock.Avalonia 11.2.0 with SukiUI.Dock 6.0.0-beta7 I ran into issues where an exception would be thrown importing the styles  `<StyleInclude Source="avares://SukiUI.Dock/Index.axaml" />`

commenting out this line caused no docked tools or document sections to show in my UI.
I tried Updating Dock.Model and Dock.Model.Avalonia in the actual  SukiUI.Dock project to 11.2.0 and referencing that dll in my project and the issues were fixed.

I would raise a PR to update these myself but I'm fairly new to avalonia and this project so I'm not really clear on any breaking changes that could be caused by upgrading these packages.

### Package Version

SukiUI.Dock 6.0.0-beta7

### Environment

Windows 11

### Expected Behavior

Able to use Dock.Avalonia 11.2.0 with the latest SukiUI.Dock 

### Reproduction

1. Create a project using Dock.Avalonia 11.2.0 and the latest SukiUI.Dock (6.0.0-beta7)
2. Import the styles `<StyleInclude Source="avares://SukiUI.Dock/Index.axaml" />` in _App.axaml_
3. Run the application and an exception will be thrown on startup
`Method not found: 'System.Collections.Generic.IReadOnlyList1<System.Object> Avalonia.Markup.Xaml.XamlIl.Runtime.IAvaloniaXamlIlEagerParentStackProvider.get_DirectParents()'`

**Comment by sirdoombox** [comment]
SukiUI.Dock is not something I've worked on personally, but I'll take a look at where everything is in terms of versioning later on. The idea is that all of SukiUI should be targeting the latest stable version of Avalonia for 6.0.0's release, I'll make sure that's the case.

It might be that SukiUI.Dock has actually had it's version properly changed, it just hasn't had a new build published in a while, either way I'll make sure everything is squared away for 6.0.0.
