### ISSUE TITLE
[Feat] Add a class selection for action buttons inside dialogs

### ISSUE THREAD

**Issue by Edgarianom1212** [kikipoulet/SukiUI#334]
### Use the search function to see if this feature has already been suggested.

- [X] I have searched for duplicate issues.

### Description of new feature

It would be nice if we would change the class of the action button inside a dialog. 

The default class of the button is statically set to "Flat", which looks bad for my application because I want to achieve a "Visual-Studio-Like" theme which has a white primary color and a dark accent together with the flat background style.

This leads to the button being completely white with the "Flat" class

For reference my dialog looks like this:

![image](https://github.com/user-attachments/assets/69d1f863-fd1a-470b-8ed5-46319a3e9a34)

### Package Version

6.0.0-rc

**Comment by kikipoulet** [comment]
Hi guys, 

A little bit off-topic but I saw this about a white-black theme.
As I like the [shadcn library](https://ui.shadcn.com/), I tried to add some trick to make a special shadcn theme for SukiUI.

![shad](https://github.com/user-attachments/assets/0673ea09-814e-44aa-a5c7-5de97009213f)

Maybe I will do some specific shadcn style files to add for a theme like that.

**Comment by kikipoulet** [comment]
I pushed the changes in the last commit.

To test the "shadcn mode", just call "Shadcn.Configure" in the Application class (it is commented in SukiUI Demo) : 

![{39E25A6B-8EB9-439F-90F5-EDD244F751FE}](https://github.com/user-attachments/assets/278f2a54-1973-462c-894d-f7bdf134bb46)


It's a little mess with styles addition/changes for some controls but let's say it's an experiment for high contrast needs, and has zero influence on SukiUI if Shadcn is not called of course.

![{F306B114-5110-43A5-8863-B6F443EB77AB}](https://github.com/user-attachments/assets/262544dc-c6bd-43ec-9062-93094e6d1107)

![{31212710-7A64-48E8-9AE0-AFCF86A178F6}](https://github.com/user-attachments/assets/9b7bc0ef-d447-400a-968b-693e52a7a3ea)

![{9044A714-6AD7-4717-BEE5-49307ABBB18D}](https://github.com/user-attachments/assets/b40b8700-02c6-4747-8a28-bc2d152e7ac3)

![{1DEB4C20-867C-4BA9-A28D-3D3C5976E0ED}](https://github.com/user-attachments/assets/ea68baeb-264d-41bd-93e6-fcc8a8f99f62)
