### ISSUE TITLE
ComboBox button clipping

### ISSUE THREAD

**Issue by montex12** [kikipoulet/SukiUI#34]
Hello,

I noticed when hovering ComboBox button it clips on margins:
![image](https://github.com/kikipoulet/SukiUI/assets/133593308/463af270-8776-49d3-a629-8ffea8af36c9)

The button doesn't follow ComboBox's CornerRadius.

With Avalonia DevTools:
```
ComboBox.CornerRadius: 6,6,6,6
ToggleButton.CornerRadius: 0,0,0,0
```

**Comment by kikipoulet** [comment]
fixed in 68be937a8fef99730236f403dcc9184969297469
