### ISSUE TITLE
[Bug] NumericUpDown Background and Border is set wrong

### ISSUE THREAD

**Issue by Edgarianom1212** [kikipoulet/SukiUI#340]
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

When setting the Background or Border of a NumericUpDown, the actual Border and Background are not set, only the part where the value is located, see below:

Output: 
![image](https://github.com/user-attachments/assets/55860998-7ccb-4d87-a007-f029ae5e4cdc)

### Package Version

6.0.0-rc

### Environment

Windows 10

### Expected Behavior

The whole background should be set to the right color and backgroundBrush.

### Reproduction

Set the Background and Border of the NumericUpDown

**Comment by kikipoulet** [comment]
05c6ecf205ffa0137a5950bee4d5d9baa77738ae
