### ISSUE TITLE
Linux window decoration

### ISSUE THREAD

**Issue by Saschanski** [kikipoulet/SukiUI#37]
Under Linux (Wayland?) theres no way to hide the system title bar as far as I know. Would it be possible to change allow hiding the Close button or hide the resulting gap altogether (including the top left corner radius)? 

I guess a workaround would be to just not use DesktopPage but that would also disable the (working) custom title bar under windows. 

This is latest Gnome using wayland
![screencap](https://github.com/kikipoulet/SukiUI/assets/1208566/0106de60-68df-410b-89e8-bd7c5327e9c1)

**Comment by kikipoulet** [comment]
You can set the "WinUIStyle" property to False and remove the DesktopPage control for a better result with native title bar

We don't have lots of alternatives here :(
