### ISSUE TITLE
Problems encountered using Groupbox

### ISSUE THREAD

**Issue by wmchuang** [kikipoulet/SukiUI#39]
![image](https://github.com/kikipoulet/SukiUI/assets/25163291/c74ed627-a5e9-44f8-91d5-7ae228150e8a)

![image](https://github.com/kikipoulet/SukiUI/assets/25163291/e176656b-3a9f-4f9e-bc07-8e559011e1ea)

I want to achieve this effect， Then I made some modifications, and I think using grid is better than using stackpanel. Do you think so?

**Comment by kikipoulet** [comment]
I think you're right, you can make a PR if you want.

**Comment by wmchuang** [comment]
Okay, I'm happy to do this
