### ISSUE TITLE
native aot support

### ISSUE THREAD

**Issue by charleypeng** [kikipoulet/SukiUI#43]
This project is wonderful!  But in AOT compilation, the controls are lost, mostly the information is shown as below

> Trim analysis warning IL2026: SukiUI.Controls.SideMenu.XamlClosure_29.Build(IServiceProvider): Using member 'Avalonia.Markup.Xaml.MarkupExtensions.ReflectionBindingExtension.ReflectionBindingExtension(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. BindingExpression and ReflectionBinding heavily use reflection. Consider using CompiledBindings instead. 

So I think maybe we shall change something to make it work.

P.S the official controls are just working fine.

**Comment by R-YaTian** [comment]
I think this is not a SukiUI issue, it works all fine for me when "PublishAot".
You should remove all uses of "x:CompileBindings='True'" from your project's axaml files, in my view. :p
