### ISSUE TITLE
TimePicker and CalendarDatePicker are not styled

### ISSUE THREAD

**Issue by DmitryGolubenkov** [kikipoulet/SukiUI#44]
# Description
`TimePicker` and `CalendarDatePicker` have no styling in SukiUI, and because of that these controls look very bad and noticeable. And if you use Dark theme, the controls become much less readable due to font color changes

<details><summary>Images</summary>

![image](https://github.com/kikipoulet/SukiUI/assets/31821994/6d3b25c9-0bfa-4103-9b7a-d9b3ef1afbb3) 

![image](https://github.com/kikipoulet/SukiUI/assets/31821994/f5c760c2-696d-4b10-9668-0c162e79ec15)  

![image](https://github.com/kikipoulet/SukiUI/assets/31821994/1b555b11-1aab-405e-a63d-ee1697c05c5e)

![image](https://github.com/kikipoulet/SukiUI/assets/31821994/fbd51e78-6cdc-4dff-87bc-843cadd5725b)

![image](https://github.com/kikipoulet/SukiUI/assets/31821994/b29d34d2-0c36-4759-a88a-1007bdd7b856)

</details> 

Maybe I'll try to add styles myself in future but I'm not an expert in any frontend things

# Other things
FYI, `Avalonia.Web` is now obsolete and instead [Avalonia.Browser](https://www.nuget.org/packages/Avalonia.Browser/) should be used

**Comment by kikipoulet** [comment]
I'll consider working on styling these when I will have time, it could be a nice addition

**Comment by darcome** [comment]
Hi!

Just a consideration... If you can't style them, basically they are useless for those who use dark themes :(

**Comment by kikipoulet** [comment]
> Hi!
> 
> Just a consideration... If you can't style them, basically they are useless for those who use dark themes :(

Work is done to theme them.

See commit 794cd9632994d104291989eb99270e1bf62bc368 that push a first draft of the calendar control.
