### ISSUE TITLE
Styling Expander and TabItem headers

### ISSUE THREAD

**Issue by mightypanda** [kikipoulet/SukiUI#47]
Hello!
Thank you for this great UI kit @kikipoulet 
I am looking to style the **header** of both Expander and TabItem, do you have any guidance?

**Comment by kikipoulet** [comment]
Hello !
I will replace the TextBlock with a contentcontrol in the controltemplate so you will be able to use this way : 

https://pastebin.com/T0sK245d

If it sounds good to you

**Comment by mightypanda** [comment]
Thank you! that sounds amazing :)

**Comment by kikipoulet** [comment]
I will update a new nuget package in 3-4 days when I will have finished a new control "Settings Layout", so I don't multiply nuget releases

**Comment by kikipoulet** [comment]
You can try it in nuget 5.0.5

**Comment by mightypanda** [comment]
Thank you so much for your dedication!
Do you think also GroupBox Header can be extended this way in a future release?
Thank you!

**Comment by kikipoulet** [comment]
> Thank you so much for your dedication! Do you think also GroupBox Header can be extended this way in a future release? Thank you!

Done in 5.0.8 :)
