### ISSUE TITLE
Stepper not styled after 5.0

### ISSUE THREAD

**Issue by ErrorVdept** [kikipoulet/SukiUI#49]
Stepper not have style (or style has been changed in latest version).
In 5.0 version stepper have style on the bottom picture.
![image](https://github.com/kikipoulet/SukiUI/assets/74969707/92907156-095c-4182-979a-4ffab855aca5)

in 5.0 version 
![image](https://github.com/kikipoulet/SukiUI/assets/74969707/c952cbd1-6b10-4fdf-9a88-bac7123704f1)

**Comment by kikipoulet** [comment]
Stepper style has been indeed updated in recent version to be lighter.
If you miss the old style, you can retrieve the old Stepper code in a previous commit
