### ISSUE TITLE
Which project can show your cute cat?

### ISSUE THREAD

**Issue by ZSYMAX** [kikipoulet/SukiUI#50]

**Comment by kikipoulet** [comment]
🤣 

While waiting for the next UI Library named by my cat, you can see it here :

https://drive.filen.io/f/9d50723c-f889-4123-83c2-5a82f63a8fb3#0URB11ucv3ZCyEH0WBK8Zc4tDQj7rk4t

**Comment by kikipoulet** [comment]
Oooopss 👀

https://github.com/kikipoulet/CherylUI 👀

**Comment by ZSYMAX** [comment]
sooooooooooo cute
