### ISSUE TITLE
Icon problems

### ISSUE THREAD

**Issue by mightypanda** [kikipoulet/SukiUI#53]
Hello,
I recently upgraded to the latest SukiUI, but i get some sort of weird behaviour with embedded icons, for example this is an expander.

![image](https://github.com/kikipoulet/SukiUI/assets/2495071/1e846e2e-84c3-4985-bf7f-e9f0c6381670)

These are the combobox checkmarks

![image](https://github.com/kikipoulet/SukiUI/assets/2495071/4520ae70-3e45-4620-b27e-7a8ab5339ad7)

I never changed anything, used to have normal looking "plus" signs for expander and tick marks for checkboxes.
Also, reverting to the older release doesn't seem to fix the thing now.

Any ideas?
Thank you

**Comment by kikipoulet** [comment]
This is definitely .. interesting 👀

My bet is that MaterialIcons nuget version is not the same one as used in SukiUI, and maybe there are more icons now in the newest version so if the icon kind is an enum, the icons could have been shifted, so you get the wrong ones in the index. (despite this nice comet)

Maybe try to install manually materialicons to the newest version.

Please note that SukiUI is still changing with new features and deeper design (glasssmorphism introduced in last version for example), so indeed big changes can happen between versions, and I hope it's for the best. So thank you for your patience 👍

**Comment by mightypanda** [comment]
Hello Clement,
Thank you so much, it was the MaterialIcons nuget i had in my project, once removed everything started to work again.

There is another issue i am having, not related to icons, will create a GIF to show you in a new github issue.

Your UI kit rocks! thank you!
