### ISSUE TITLE
Strange ComboBox animation behaviour

### ISSUE THREAD

**Issue by mightypanda** [kikipoulet/SukiUI#54]
Hello!
I am getting this strange visual behaviour when opening comboboxes.
The strange thing is that the cointaining element is a grid (the gray panel with extender) so i don't see how the element could span for the whole width of the uppermost container.
Any ideas?

As a workaround, how could I disable the opening animation trying  to fix it?

Thank you!

https://github.com/kikipoulet/SukiUI/assets/2495071/3b7fa50c-7cbd-4669-8242-2cf147d4d658

**Comment by mightypanda** [comment]
As a side note, I would also need to remove those X icons on the numeric textboxes

**Comment by kikipoulet** [comment]
I took your feedback in account but unfortunately I'm working right now on next release which add glassmorphism by default.
So if you want to check if removing the transition work, you can just add this style in your app : 

https://pastebin.com/RgxfQkg4

It's the same combobox without the transition.

**Comment by mightypanda** [comment]
Thank you so much!
I tried it but it seems there is some error in the xaml..
