### ISSUE TITLE
WaveProgress text foreground is not updated when switch theme

### ISSUE THREAD

**Issue by jeff9571** [kikipoulet/SukiUI#58]
In light theme the text foreground is black:
![image](https://github.com/kikipoulet/SukiUI/assets/35749706/434be4a6-f6d3-49ec-b68a-f7880442434f)
When I switched to dark theme, the text foreground is still black:
![image](https://github.com/kikipoulet/SukiUI/assets/35749706/041b2964-f104-4897-923b-322f3b80dfea)
But when I changed the value of the waveprogress, the text foreground will turn to white:
![image](https://github.com/kikipoulet/SukiUI/assets/35749706/ec43dc37-b0e6-4f01-9c7d-6bed369de369)
How to make the goal that When I switch the light theme to drak theme, the text foreground will auto turn to white, instead change the value manually? Thanks.

**Comment by kikipoulet** [comment]
good observation, fixed in commit ff4639f
