### ISSUE TITLE
Consider a move to making SukiWindow as the new default.

### ISSUE THREAD

**Issue by sirdoombox** [kikipoulet/SukiUI#60]
I've been experimenting locally with making a `SukiWindow` control and theme, removing `DesktopPage` and `InteractiveContainer` from the stack entirely, folding their features into the new `SukiWindow`

This change means that the `NakedWindow` style will be the standard for everyone, and core Window features can be depended on to exist as `SukiWindow` will be the base requirement for any _SukiUI_ based app.

The move to desktop only (for what I guess will end up being a 6.0 release at this point) is a good opportunity to make major breaking changes that would make dev experience smoother, no more need for the secret sauce combination of `NakedWindow` class applied to a window, containing a `DesktopPage` with an `InteractiveContainer` inside.

I'm happy to work on this personally, I've got something basic running locally just need to reorganise everything, but obviously this will be a fairly significant breaking change.

**Comment by kikipoulet** [comment]
Well showed like that I agree 👍

And for 6.0 focused on desktop only .. that was precisely my goal. Focusing on desktop, removing obsolete mobile controls, polishing last details to make SukiUI more than a UI Theme but a real complete toolkit to make modern richly animated apps easily.

So yes, it's definitely a smart move, let's do that

**Comment by sirdoombox** [comment]
Fixed by #62
