### ISSUE TITLE
There are extra icons appeared when closing the side menu

### ISSUE THREAD

**Issue by jeff9571** [kikipoulet/SukiUI#61]
The following screenshot is closing the side menu:
![1703737458611](https://github.com/kikipoulet/SukiUI/assets/35749706/412d9b0c-918f-4f91-8dde-92f3df208f5c)

**Comment by kikipoulet** [comment]
thank you for your observation, fixed in commit e0dee48

**Comment by jeff9571** [comment]
> thank you for your observation, fixed in commit [e0dee48](https://github.com/kikipoulet/SukiUI/commit/e0dee4829f6c49d7dd138e20a10f02e29b357edf)

Thanks for making such beautiful avalonia controls, btw，when will version 6.0 be released？

**Comment by kikipoulet** [comment]
> > thank you for your observation, fixed in commit [e0dee48](https://github.com/kikipoulet/SukiUI/commit/e0dee4829f6c49d7dd138e20a10f02e29b357edf)
> 
> Thanks for making such beautiful avalonia controls, btw，when will version 6.0 be released？

We're polishing the last controls and make the last breaking changes before 6.0, it's why I still wait.

I will upload 6.0 next week, at least a preview, but 'real' launch will be when the new sukidemo app will be ready. It will show dynamically every controls, their functionalities and their code, setting the documentation almost unnecessary.
