### ISSUE TITLE
Expanding Multiline Text Blocks

### ISSUE THREAD

**Issue by AnimatedSwine37** [kikipoulet/SukiUI#90]
When creating a text block that accepts multiple lines by setting `AcceptsReturn` to `True` I'd expect it to expand it's height to fit multiple lines as this is what the default Avalonia control does. Instead, with the latest version of SukiUI (built myself from the repo) a scroll bar will appear and the text block will always stay at one line.

**Comment by kikipoulet** [comment]
fixed in commit 79e14f4
